import type { NicheDefinition, NicheFamily, NicheId } from "./types";

type Seed = Omit<NicheDefinition, never>;
const n = (s: Seed) => s;

export const NICHES_BEAUTY: Record<string, NicheDefinition> = {
  salon: n({
    id: "salon",
    label: "Salon",
    family: "beauty",
    mapsSearches: ["hair salon", "beauty parlor"],
    tagline: "Hair, beauty & bridal care",
    heroTitle: "Look fresh. Book your salon slot online.",
    heroSubtitle: "Haircut, styling, facial, party makeup and bridal packages — WhatsApp booking.",
    ctaPrimary: "Book appointment",
    ctaSecondary: "View services",
    bookingLabel: "Book salon visit",
    servicesTitle: "Salon services",
    services: [
      { title: "Haircut & styling", description: "Ladies cuts, blow-dry, party styles.", priceFrom: "Rs 1,500", popular: true },
      { title: "Hair color & highlights", description: "Global, highlights, balayage with patch test.", priceFrom: "Rs 4,500" },
      { title: "Facial & cleanup", description: "Cleanup, whitening and glow facials.", priceFrom: "Rs 2,500" },
      { title: "Party / bridal makeup", description: "HD makeup, hair and draping packages.", priceFrom: "Rs 8,000" },
      { title: "Manicure & pedicure", description: "Classic, gel and spa pedicure.", priceFrom: "Rs 1,800" },
      { title: "Threading & waxing", description: "Face, arms, legs — hygienic wax.", priceFrom: "Rs 400" },
      { title: "Keratin / treatment", description: "Smoothing and repair treatments.", priceFrom: "Rs 8,000" },
      { title: "Mehndi / party ready", description: "Hands, feet and party add-ons.", priceFrom: "Rs 1,200" },
    ],
    features: [
      { title: "Hygienic tools", description: "Sanitized kit for every client." },
      { title: "Bridal trials", description: "Trial slots before the big day." },
      { title: "Product choices", description: "Trusted brands for color and care." },
      { title: "Easy booking", description: "Pick time on WhatsApp — confirm instantly." },
    ],
    faqs: [
      { q: "Do you do home service?", a: "Bridal and party home service available in selected areas." },
      { q: "How to book?", a: "Tap Book and send preferred date/time on WhatsApp." },
    ],
    galleryLabels: ["Salon floor", "Hair styling", "Makeup bar", "Facial", "Bridal look", "Nails", "Color work", "Lounge"],
    trustPoints: ["Hygienic", "Bridal ready", "WhatsApp booking", "Experienced artists"],
    packages: [
      { name: "Glow", price: "Rs 4,500", items: ["Cleanup", "Hair", "Brows"] },
      { name: "Party", price: "Rs 8,000", items: ["Makeup", "Hair", "Saree/drape"], highlighted: true },
      { name: "Bridal", price: "Custom", items: ["Trial", "HD", "Hair", "Touch-up"] },
    ],
    specialSections: ["booking", "portfolio", "before-after"],
    whatsappPreset: "Assalam o Alaikum! Salon booking for: ",
  }),
  barber: n({
    id: "barber",
    label: "Barber",
    family: "beauty",
    mapsSearches: ["barber shop", "men’s grooming"],
    tagline: "Men’s haircut & grooming",
    heroTitle: "Sharp cuts. Clean fades. Walk in or book.",
    heroSubtitle: "Haircut, beard shape, facial and kids cuts with hygienic tools.",
    ctaPrimary: "Book chair",
    ctaSecondary: "See prices",
    bookingLabel: "Book barber slot",
    servicesTitle: "Grooming menu",
    services: [
      { title: "Haircut", description: "Classic, fade, scissor cut.", priceFrom: "Rs 500", popular: true },
      { title: "Beard trim", description: "Shape, line-up and hot towel options.", priceFrom: "Rs 300" },
      { title: "Hair + beard", description: "Complete grooming combo.", priceFrom: "Rs 700" },
      { title: "Facial / cleanup", description: "Men’s cleanup and blackhead care.", priceFrom: "Rs 1,200" },
    ],
    features: [
      { title: "Quick slots", description: "Book to skip the wait." },
      { title: "Kids welcome", description: "Patient cuts for children." },
      { title: "Clean blades", description: "Fresh blades / sanitized tools." },
      { title: "Style advice", description: "Cut suited to face shape." },
    ],
    faqs: [{ q: "Walk-ins accepted?", a: "Yes — booking recommended on busy evenings." }],
    galleryLabels: ["Fade", "Beard", "Classic", "Kids"],
    trustPoints: ["Fast service", "Hygienic", "Beard experts", "Fair prices"],
    packages: [
      { name: "Cut", price: "Rs 500", items: ["Haircut"] },
      { name: "Groom", price: "Rs 700", items: ["Hair + beard"], highlighted: true },
      { name: "Refresh", price: "Rs 1,800", items: ["Cut", "Beard", "Cleanup"] },
    ],
    specialSections: ["booking"],
    whatsappPreset: "Assalam o Alaikum! Barber booking: ",
  }),
  spa: n({
    id: "spa",
    label: "Spa",
    family: "beauty",
    mapsSearches: ["spa", "massage spa"],
    tagline: "Relaxing massage & spa therapies",
    heroTitle: "Unwind. Recharge. Book your spa hour.",
    heroSubtitle: "Swedish, deep tissue, aroma and couples packages in a calm setting.",
    ctaPrimary: "Book spa session",
    ctaSecondary: "View therapies",
    bookingLabel: "Book spa",
    servicesTitle: "Spa therapies",
    services: [
      { title: "Swedish massage", description: "Full body relaxation massage.", priceFrom: "Rs 4,000", popular: true },
      { title: "Deep tissue", description: "For tension and desk-job stiffness.", priceFrom: "Rs 5,000" },
      { title: "Aroma therapy", description: "Scented oils for deep calm.", priceFrom: "Rs 4,500" },
      { title: "Couples package", description: "Side-by-side relaxation session.", priceFrom: "Rs 9,000" },
    ],
    features: [
      { title: "Private rooms", description: "Quiet, clean treatment rooms." },
      { title: "Trained therapists", description: "Professional massage techniques." },
      { title: "Hygiene focus", description: "Fresh linen and sanitized surfaces." },
      { title: "Gift vouchers", description: "Perfect for birthdays and Eid." },
    ],
    faqs: [{ q: "What should I wear?", a: "Comfortable clothes; robes provided where applicable." }],
    galleryLabels: ["Room", "Massage", "Oils", "Lounge"],
    trustPoints: ["Private", "Trained", "Hygienic", "Gift cards"],
    packages: [
      { name: "60 min", price: "Rs 4,000", items: ["Swedish"] },
      { name: "90 min", price: "Rs 5,500", items: ["Deep tissue"], highlighted: true },
      { name: "Couple", price: "Rs 9,000", items: ["Dual session"] },
    ],
    specialSections: ["booking"],
    whatsappPreset: "Assalam o Alaikum! Spa booking for: ",
  }),
  nail: n({
    id: "nail",
    label: "Nail salon",
    family: "beauty",
    mapsSearches: ["nail salon", "manicure"],
    tagline: "Manicure, pedicure & gel nails",
    heroTitle: "Nails that last — gel, art & care.",
    heroSubtitle: "Manicure, pedicure, gel extensions and nail art with sanitized tools.",
    ctaPrimary: "Book nail slot",
    ctaSecondary: "See designs",
    bookingLabel: "Book nails",
    servicesTitle: "Nail services",
    services: [
      { title: "Gel manicure", description: "Long-lasting color and shine.", priceFrom: "Rs 2,500", popular: true },
      { title: "Pedicure", description: "Foot care and polish.", priceFrom: "Rs 2,000" },
      { title: "Extensions", description: "Length and shape with gel/acrylic options.", priceFrom: "Rs 4,000" },
      { title: "Nail art", description: "Custom designs for events.", priceFrom: "Rs 500+" },
    ],
    features: [
      { title: "Sterile tools", description: "Sanitized implements every time." },
      { title: "Trend designs", description: "Browse recent nail art on WhatsApp." },
      { title: "Gentle removal", description: "Safe gel removal to protect nails." },
      { title: "Quick glam", description: "Express slots for busy days." },
    ],
    faqs: [{ q: "How long do gel nails last?", a: "Typically 2–3 weeks with proper care." }],
    galleryLabels: ["Gel", "Art", "Pedicure", "Extensions"],
    trustPoints: ["Sanitized", "Gel experts", "Art options", "Gentle care"],
    packages: [
      { name: "Classic", price: "Rs 2,000", items: ["Mani"] },
      { name: "Gel glam", price: "Rs 2,500", items: ["Gel mani"], highlighted: true },
      { name: "Hands & feet", price: "Rs 4,200", items: ["Mani + pedi"] },
    ],
    specialSections: ["booking", "portfolio"],
    whatsappPreset: "Assalam o Alaikum! Nail appointment: ",
  }),
  makeup: n({
    id: "makeup",
    label: "Makeup artist",
    family: "beauty",
    mapsSearches: ["makeup artist", "bridal makeup"],
    tagline: "Bridal & party makeup artist",
    heroTitle: "Camera-ready makeup for your day.",
    heroSubtitle: "Bridal HD, party glam and engagement looks — studio or home service.",
    ctaPrimary: "Book makeup date",
    ctaSecondary: "Ask for portfolio",
    bookingLabel: "Book MUA",
    servicesTitle: "Makeup services",
    services: [
      { title: "Party makeup", description: "Soft glam to bold evening looks.", priceFrom: "Rs 8,000", popular: true },
      { title: "Bridal HD", description: "Long-wear bridal with trial option.", priceFrom: "Custom" },
      { title: "Engagement / walima", description: "Event-specific packages.", priceFrom: "Custom" },
      { title: "Hair + makeup", description: "Complete look with styling.", priceFrom: "Custom" },
    ],
    features: [
      { title: "HD products", description: "Long-wear products for photos and heat." },
      { title: "Trials", description: "Bridal trials to lock your look." },
      { title: "Home service", description: "Available in selected city areas." },
      { title: "On-time", description: "Punctual for barat and walima timelines." },
    ],
    faqs: [{ q: "Do you travel?", a: "Yes within defined areas — travel fee may apply." }],
    galleryLabels: ["Bridal", "Party", "Engagement", "Hair"],
    trustPoints: ["HD finish", "Trials", "On-time", "Home service"],
    packages: [
      { name: "Party", price: "Rs 8,000", items: ["Makeup"] },
      { name: "Bridal", price: "Custom", items: ["Trial", "HD", "Touch-up"], highlighted: true },
      { name: "Family", price: "Custom", items: ["Multiple looks"] },
    ],
    specialSections: ["portfolio", "booking", "before-after"],
    whatsappPreset: "Assalam o Alaikum! Makeup booking for event: ",
  }),
  mehandi: n({
    id: "mehandi",
    label: "Mehandi",
    family: "beauty",
    mapsSearches: ["mehndi artist"],
    tagline: "Bridal & party mehndi artist",
    heroTitle: "Beautiful mehndi for every celebration.",
    heroSubtitle: "Bridal full-hand, party Arabic and kids designs — home or venue.",
    ctaPrimary: "Book mehndi",
    ctaSecondary: "See designs",
    bookingLabel: "Book mehndi artist",
    servicesTitle: "Mehndi styles",
    services: [
      { title: "Bridal mehndi", description: "Full hand/feet detailed bridal work.", priceFrom: "Custom", popular: true },
      { title: "Arabic / party", description: "Elegant quick designs for guests.", priceFrom: "Rs 2,500" },
      { title: "Family package", description: "Bride + sisters / guests combo.", priceFrom: "Custom" },
      { title: "Kids designs", description: "Simple cute patterns.", priceFrom: "Rs 800" },
    ],
    features: [
      { title: "Dark stain tips", description: "Aftercare for richer color." },
      { title: "Venue visits", description: "Home and wedding venue service." },
      { title: "Design catalog", description: "Pick from recent portfolios." },
      { title: "Group discounts", description: "Better rates for family packages." },
    ],
    faqs: [{ q: "How long for bridal?", a: "Often 4–8 hours depending on detail." }],
    galleryLabels: ["Bridal", "Arabic", "Feet", "Party"],
    trustPoints: ["Bridal detail", "Venue ready", "Group packs", "Aftercare"],
    packages: [
      { name: "Party", price: "Rs 2,500", items: ["Arabic"] },
      { name: "Bridal", price: "Custom", items: ["Full design"], highlighted: true },
      { name: "Family", price: "Custom", items: ["Multiple people"] },
    ],
    specialSections: ["portfolio", "booking"],
    whatsappPreset: "Assalam o Alaikum! Mehndi booking: ",
  }),
  tattoo: n({
    id: "tattoo",
    label: "Tattoo",
    family: "beauty",
    mapsSearches: ["tattoo studio"],
    tagline: "Custom tattoos & piercing",
    heroTitle: "Custom ink. Clean studio. Your design.",
    heroSubtitle: "Custom tattoos, cover-ups and piercing with strict hygiene standards.",
    ctaPrimary: "Book consult",
    ctaSecondary: "Send design idea",
    bookingLabel: "Book tattoo consult",
    servicesTitle: "Studio services",
    services: [
      { title: "Custom tattoo", description: "Design consultation to final ink.", priceFrom: "Custom", popular: true },
      { title: "Small tattoo", description: "Minimal symbols and lettering.", priceFrom: "Rs 5,000" },
      { title: "Cover-up", description: "Redesign over old tattoos.", priceFrom: "Custom" },
      { title: "Piercing", description: "Ear and selected piercings.", priceFrom: "Rs 2,500" },
    ],
    features: [
      { title: "Sterile process", description: "Single-use needles and sanitized station." },
      { title: "Custom art", description: "Design with you before inking." },
      { title: "Aftercare kit", description: "Clear healing instructions." },
      { title: "Private studio", description: "Comfortable appointment-based visits." },
    ],
    faqs: [{ q: "Walk-ins?", a: "Consult preferred — walk-ins if artist is free." }],
    galleryLabels: ["Custom", "Minimal", "Cover-up", "Studio"],
    trustPoints: ["Sterile", "Custom art", "Aftercare", "Appointment based"],
    packages: [
      { name: "Small", price: "Rs 5,000+", items: ["Simple design"] },
      { name: "Custom session", price: "Custom", items: ["Design + ink"], highlighted: true },
      { name: "Piercing", price: "Rs 2,500+", items: ["Piercing + care"] },
    ],
    specialSections: ["portfolio", "booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! Tattoo consult — idea: ",
  }),
  skincare: n({
    id: "skincare",
    label: "Skincare / dermat clinic",
    family: "beauty",
    mapsSearches: ["skin clinic", "dermatologist"],
    tagline: "Skin clinic & aesthetic care",
    heroTitle: "Clearer skin with doctor-led care.",
    heroSubtitle: "Acne, pigmentation, cleanup and aesthetic treatments with proper consultation.",
    ctaPrimary: "Book skin consult",
    ctaSecondary: "WhatsApp concern",
    bookingLabel: "Book clinic visit",
    servicesTitle: "Skin treatments",
    services: [
      { title: "Dermat consult", description: "Examination and treatment plan.", priceFrom: "Rs 2,000", popular: true },
      { title: "Acne care", description: "Plan for active acne and marks.", priceFrom: "Custom" },
      { title: "Cleanup / facial medical", description: "Clinic-grade cleanup.", priceFrom: "Rs 3,500" },
      { title: "Pigmentation", description: "Assessment and session-based care.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Consult first", description: "No blind treatments — assessment first." },
      { title: "Progress tracking", description: "Follow-ups for visible results." },
      { title: "Hygiene clinic", description: "Clinical cleanliness standards." },
      { title: "Honest advice", description: "We say what you need — not upsell everything." },
    ],
    faqs: [{ q: "Are walk-ins ok?", a: "Appointments preferred to reduce waiting." }],
    galleryLabels: ["Clinic", "Consult", "Treatment", "Aftercare"],
    trustPoints: ["Consult-led", "Follow-ups", "Clinical hygiene", "Clear plans"],
    packages: [
      { name: "Consult", price: "Rs 2,000", items: ["Assessment"] },
      { name: "Acne plan", price: "Custom", items: ["Sessions + products"], highlighted: true },
      { name: "Glow sessions", price: "Custom", items: ["3–6 sessions"] },
    ],
    specialSections: ["booking", "consultation", "before-after"],
    whatsappPreset: "Assalam o Alaikum! Skin consult for: ",
  }),
};

// silence unused import if tree shakes
void (0 as unknown as NicheFamily | NicheId);
