import type { NicheDefinition } from "./types";

const n = (s: NicheDefinition) => s;

export const NICHES_AUTO: Record<string, NicheDefinition> = {
  "car-wash": n({
    id: "car-wash",
    label: "Car wash",
    family: "auto",
    mapsSearches: ["car wash", "detailing"],
    tagline: "Car wash & detailing",
    heroTitle: "Showroom shine without the wait.",
    heroSubtitle: "Exterior wash, interior detail and ceramic options — book your slot.",
    ctaPrimary: "Book car wash",
    ctaSecondary: "See packages",
    bookingLabel: "Book wash / detail",
    servicesTitle: "Wash packages",
    services: [
      { title: "Exterior wash", description: "Foam wash and dry.", priceFrom: "Rs 800", popular: true },
      { title: "Interior detail", description: "Vacuum, dashboard, mats.", priceFrom: "Rs 1,500" },
      { title: "Full detail", description: "Inside-out deep clean.", priceFrom: "Rs 3,500" },
      { title: "Ceramic / polish", description: "Shine and protection packages.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Slot booking", description: "Skip the queue." },
      { title: "Careful detailing", description: "No rough brush damage." },
      { title: "Bike & car", description: "Two-wheeler options where offered." },
      { title: "Before/after", description: "See the difference." },
    ],
    faqs: [{ q: "How long for full detail?", a: "Usually 2–4 hours depending on vehicle." }],
    galleryLabels: ["Foam", "Interior", "Polish", "Finish"],
    trustPoints: ["Booked slots", "Detailing", "Careful wash", "Packages"],
    packages: [
      { name: "Express", price: "Rs 800", items: ["Exterior"] },
      { name: "Full detail", price: "Rs 3,500", items: ["Inside-out"], highlighted: true },
      { name: "Ceramic", price: "Custom", items: ["Protection"] },
    ],
    specialSections: ["booking", "before-after"],
    whatsappPreset: "Assalam o Alaikum! Car wash booking — car: ",
  }),
  mechanic: n({
    id: "mechanic",
    label: "Mechanic",
    family: "auto",
    mapsSearches: ["car mechanic", "bike mechanic"],
    tagline: "Car & bike mechanic workshop",
    heroTitle: "Honest workshop repairs you can trust.",
    heroSubtitle: "Service, diagnostics, oil change and repair for cars and bikes.",
    ctaPrimary: "Book service",
    ctaSecondary: "Send car issue",
    bookingLabel: "Book mechanic",
    servicesTitle: "Workshop services",
    services: [
      { title: "General service", description: "Oil, filters, basic checkup.", priceFrom: "Rs 3,500", popular: true },
      { title: "Diagnostics", description: "Find engine/electrical faults.", priceFrom: "Rs 1,500" },
      { title: "Brake & suspension", description: "Safety critical repairs.", priceFrom: "Custom" },
      { title: "Bike service", description: "Tune-up and repairs for motorcycles.", priceFrom: "Rs 1,200" },
    ],
    features: [
      { title: "Transparent parts", description: "Approve parts before install." },
      { title: "Update on WhatsApp", description: "Status while your car is in bay." },
      { title: "Car & bike", description: "Multi-vehicle experience." },
      { title: "Quality oils", description: "Recommended grade guidance." },
    ],
    faqs: [{ q: "Do you pick/drop?", a: "In some areas — ask when booking." }],
    galleryLabels: ["Bay", "Service", "Bike", "Diagnostics"],
    trustPoints: ["Honest estimate", "WhatsApp updates", "Car + bike", "Safety focus"],
    packages: [
      { name: "Basic service", price: "Rs 3,500+", items: ["Oil service"] },
      { name: "Full checkup", price: "Custom", items: ["Diagnose + fix"], highlighted: true },
      { name: "Bike tune", price: "Rs 1,200+", items: ["Service"] },
    ],
    specialSections: ["booking", "warranty", "emergency"],
    whatsappPreset: "Assalam o Alaikum! Mechanic needed — vehicle/issue: ",
  }),
  tyre: n({
    id: "tyre",
    label: "Tyre",
    family: "auto",
    mapsSearches: ["tyre shop"],
    tagline: "Tyres, alignment & puncture",
    heroTitle: "Tyres fitted right. Alignment that lasts.",
    heroSubtitle: "New tyres, puncture repair, balancing and wheel alignment.",
    ctaPrimary: "Ask tyre price",
    ctaSecondary: "Book alignment",
    bookingLabel: "Book tyre service",
    servicesTitle: "Tyre services",
    services: [
      { title: "New tyres", description: "Popular brands for cars and bikes.", priceFrom: "Custom", popular: true },
      { title: "Puncture repair", description: "Quick puncture and patch.", priceFrom: "Rs 200" },
      { title: "Wheel alignment", description: "Improve tyre life and handling.", priceFrom: "Rs 1,500" },
      { title: "Balancing", description: "Smooth ride, less vibration.", priceFrom: "Rs 800" },
    ],
    features: [
      { title: "Brand choice", description: "Budget to premium tyre options." },
      { title: "Quick puncture", description: "Fast turnaround." },
      { title: "Alignment tech", description: "Proper machine alignment." },
      { title: "Advice first", description: "We tell you repair vs replace." },
    ],
    faqs: [{ q: "Do you keep stock?", a: "Common sizes usually available — confirm size." }],
    galleryLabels: ["Tyres", "Alignment", "Balancing", "Shop"],
    trustPoints: ["Brand options", "Alignment", "Fast puncture", "Honest advice"],
    packages: [
      { name: "Puncture", price: "Rs 200+", items: ["Repair"] },
      { name: "Align + balance", price: "Rs 2,200", items: ["Both"], highlighted: true },
      { name: "Tyre set", price: "Custom", items: ["Supply + fit"] },
    ],
    specialSections: ["booking", "emergency"],
    whatsappPreset: "Assalam o Alaikum! Tyre/alignment — size: ",
  }),
  "driving-school": n({
    id: "driving-school",
    label: "Driving school",
    family: "auto",
    mapsSearches: ["driving school"],
    tagline: "Learn driving with confidence",
    heroTitle: "Learn to drive — patient instructors, clear package.",
    heroSubtitle: "Beginner car lessons, ladies batches and license guidance support.",
    ctaPrimary: "Join driving class",
    ctaSecondary: "Ask package fees",
    bookingLabel: "Enroll driving course",
    servicesTitle: "Driving courses",
    services: [
      { title: "Beginner package", description: "Core lessons for new drivers.", priceFrom: "Rs 12,000", popular: true },
      { title: "Ladies batch", description: "Comfortable learning environment.", priceFrom: "Custom" },
      { title: "Refresh lessons", description: "For rusty drivers.", priceFrom: "Rs 1,500/class" },
      { title: "License guidance", description: "Help navigating the process.", priceFrom: "—" },
    ],
    features: [
      { title: "Patient instructors", description: "Calm teaching style." },
      { title: "Dual control cars", description: "Safer learning where available." },
      { title: "Flexible timing", description: "Morning/evening slots." },
      { title: "City roads", description: "Real traffic practice." },
    ],
    faqs: [{ q: "Car provided?", a: "Yes for training packages." }],
    galleryLabels: ["Lesson", "Car", "Instructor", "Practice"],
    trustPoints: ["Patient teaching", "Packages", "Ladies option", "Real roads"],
    packages: [
      { name: "Starter", price: "Rs 12,000", items: ["Lessons"] },
      { name: "Complete", price: "Custom", items: ["More hours"], highlighted: true },
      { name: "Refresh", price: "Rs 1,500", items: ["Per class"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Driving school enrollment: ",
  }),
  taxi: n({
    id: "taxi",
    label: "Taxi / cab",
    family: "auto",
    mapsSearches: ["taxi service", "cab service"],
    tagline: "City rides & outstation cabs",
    heroTitle: "Reliable cab when you need to move.",
    heroSubtitle: "Airport runs, city rides and outstation trips — book on WhatsApp.",
    ctaPrimary: "Book a cab",
    ctaSecondary: "Ask outstation rate",
    bookingLabel: "Book taxi",
    servicesTitle: "Ride options",
    services: [
      { title: "City ride", description: "Point-to-point within city.", priceFrom: "Custom", popular: true },
      { title: "Airport transfer", description: "On-time airport pickup/drop.", priceFrom: "Custom" },
      { title: "Outstation", description: "Intercity trips with waiting options.", priceFrom: "Custom" },
      { title: "Hourly hire", description: "Half-day / full-day packages.", priceFrom: "Custom" },
    ],
    features: [
      { title: "On-time focus", description: "Especially for flights." },
      { title: "Clean cars", description: "Comfortable AC vehicles." },
      { title: "WhatsApp booking", description: "Share pickup pin easily." },
      { title: "Fixed outstation", description: "Clear rates before travel." },
    ],
    faqs: [{ q: "Night charges?", a: "Shared transparently when booking." }],
    galleryLabels: ["Sedan", "Airport", "Outstation", "Fleet"],
    trustPoints: ["On-time", "Airport pro", "Outstation", "WhatsApp book"],
    packages: [
      { name: "City", price: "Meter/fixed", items: ["Local"] },
      { name: "Airport", price: "Fixed", items: ["Transfer"], highlighted: true },
      { name: "Outstation", price: "Custom", items: ["Per km/day"] },
    ],
    specialSections: ["booking"],
    whatsappPreset: "Assalam o Alaikum! Cab needed — pickup/drop: ",
  }),
  towing: n({
    id: "towing",
    label: "Towing",
    family: "auto",
    mapsSearches: ["towing service"],
    tagline: "Vehicle towing & roadside help",
    heroTitle: "Breakdown? We’ll tow you safely.",
    heroSubtitle: "Car and bike towing, jump-start and roadside assistance.",
    ctaPrimary: "Call for tow",
    ctaSecondary: "Share location",
    bookingLabel: "Request towing",
    servicesTitle: "Roadside services",
    services: [
      { title: "Car towing", description: "Safe tow to workshop/home.", priceFrom: "Custom", popular: true },
      { title: "Bike towing", description: "Motorcycle recovery.", priceFrom: "Custom" },
      { title: "Jump-start", description: "Battery boost help.", priceFrom: "Rs 1,500" },
      { title: "Workshop drop", description: "Direct to preferred mechanic.", priceFrom: "—" },
    ],
    features: [
      { title: "GPS location", description: "Share pin for faster arrival." },
      { title: "Careful loading", description: "Protect undercarriage and body." },
      { title: "Day & night", description: "Emergency response focus." },
      { title: "Clear distance rate", description: "Quote before hooking." },
    ],
    faqs: [{ q: "How fast?", a: "Depends on traffic and distance — ETA shared on call." }],
    galleryLabels: ["Tow truck", "Loading", "Bike tow", "Night"],
    trustPoints: ["Emergency", "Careful tow", "Bike + car", "Clear rates"],
    packages: [
      { name: "Local tow", price: "Custom", items: ["City"] },
      { name: "Long distance", price: "Custom", items: ["Per km"], highlighted: true },
      { name: "Jump-start", price: "Rs 1,500+", items: ["Boost"] },
    ],
    specialSections: ["emergency", "booking"],
    whatsappPreset: "Assalam o Alaikum! Towing needed — location: ",
  }),
  "car-ac": n({
    id: "car-ac",
    label: "Car AC",
    family: "auto",
    mapsSearches: ["car AC repair"],
    tagline: "Car AC gas & repair",
    heroTitle: "Car AC not cooling? Fix it today.",
    heroSubtitle: "Gas refill, leak check, cooling coil and compressor diagnosis.",
    ctaPrimary: "Book car AC service",
    ctaSecondary: "Describe cooling issue",
    bookingLabel: "Book car AC",
    servicesTitle: "Car AC services",
    services: [
      { title: "Gas refill", description: "Proper vacuum and gas.", priceFrom: "Rs 4,000", popular: true },
      { title: "Leak detection", description: "Find why cooling drops.", priceFrom: "Rs 1,500" },
      { title: "Full service", description: "Clean, check and recharge.", priceFrom: "Custom" },
      { title: "Compressor work", description: "Repair/replace guidance.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Cooling test", description: "Verify vent temperature after service." },
      { title: "Honest diagnosis", description: "Gas vs parts — clear advice." },
      { title: "Quick slots", description: "Summer priority booking." },
      { title: "All common cars", description: "Local popular models." },
    ],
    faqs: [{ q: "How long?", a: "Gas service often under 2 hours if no major leak." }],
    galleryLabels: ["Gauge", "Service", "Vent test", "Bay"],
    trustPoints: ["Cooling verified", "Leak find", "Summer ready", "Clear advice"],
    packages: [
      { name: "Gas", price: "Rs 4,000+", items: ["Refill"] },
      { name: "Diagnose + gas", price: "Custom", items: ["Full check"], highlighted: true },
      { name: "Major repair", price: "Custom", items: ["Parts + labor"] },
    ],
    specialSections: ["booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! Car AC service — model/issue: ",
  }),
};

export const NICHES_EDUCATION: Record<string, NicheDefinition> = {
  tuition: n({
    id: "tuition",
    label: "Tuition",
    family: "education",
    mapsSearches: ["tuition center", "coaching"],
    tagline: "Tuition & coaching center",
    heroTitle: "Better grades with focused coaching.",
    heroSubtitle: "Matric, intermediate and subject tuition with small batches and progress updates.",
    ctaPrimary: "Enroll / inquire",
    ctaSecondary: "Ask subjects & fees",
    bookingLabel: "Register for tuition",
    servicesTitle: "Courses",
    services: [
      { title: "Matric coaching", description: "Board-focused preparation.", priceFrom: "Custom", popular: true },
      { title: "Intermediate", description: "FSc / FA subject support.", priceFrom: "Custom" },
      { title: "Individual tuition", description: "1-on-1 home/online options.", priceFrom: "Custom" },
      { title: "Test series", description: "Regular assessments.", priceFrom: "—" },
    ],
    features: [
      { title: "Small batches", description: "More attention per student." },
      { title: "Parent updates", description: "Progress shared periodically." },
      { title: "Notes & tests", description: "Structured study material." },
      { title: "Experienced teachers", description: "Subject specialists." },
    ],
    faqs: [{ q: "Online classes?", a: "Ask for current online/hybrid options." }],
    galleryLabels: ["Classroom", "Notes", "Test", "Batch"],
    trustPoints: ["Small batches", "Parent updates", "Tests", "Subject experts"],
    packages: [
      { name: "Monthly", price: "Custom", items: ["Subject"] },
      { name: "Full term", price: "Custom", items: ["Board prep"], highlighted: true },
      { name: "1-on-1", price: "Custom", items: ["Private"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Tuition inquiry — class/subject: ",
  }),
  school: n({
    id: "school",
    label: "School",
    family: "education",
    mapsSearches: ["play school", "preschool"],
    tagline: "Play school & early learning",
    heroTitle: "A happy start for little learners.",
    heroSubtitle: "Play-based preschool with caring teachers and safe classrooms.",
    ctaPrimary: "Book school tour",
    ctaSecondary: "Ask admission",
    bookingLabel: "Book campus visit",
    servicesTitle: "Programs",
    services: [
      { title: "Playgroup", description: "Early social and motor skills.", priceFrom: "Custom", popular: true },
      { title: "Nursery / KG", description: "Foundation learning years.", priceFrom: "Custom" },
      { title: "Daycare add-on", description: "Extended hours where available.", priceFrom: "Custom" },
      { title: "Trial day", description: "Let your child experience a class.", priceFrom: "—" },
    ],
    features: [
      { title: "Safe campus", description: "Child-safe environment focus." },
      { title: "Caring staff", description: "Warm early-years teachers." },
      { title: "Activity based", description: "Learning through play." },
      { title: "Parent communication", description: "Updates on progress." },
    ],
    faqs: [{ q: "Admission open?", a: "Message for current seats and fees." }],
    galleryLabels: ["Classroom", "Play", "Activity", "Kids"],
    trustPoints: ["Safe", "Play-based", "Caring teachers", "Parent updates"],
    packages: [
      { name: "Term fees", price: "Custom", items: ["Program"] },
      { name: "Admission", price: "Custom", items: ["One-time"], highlighted: true },
      { name: "Trial", price: "—", items: ["Visit"] },
    ],
    specialSections: ["classes", "booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! School admission/tour: ",
  }),
  music: n({
    id: "music",
    label: "Music",
    family: "education",
    mapsSearches: ["music classes"],
    tagline: "Music classes for all ages",
    heroTitle: "Learn music — instrument or vocals.",
    heroSubtitle: "Guitar, keyboard, vocals and beginner batches with weekly practice.",
    ctaPrimary: "Join music class",
    ctaSecondary: "Ask instruments",
    bookingLabel: "Enroll music",
    servicesTitle: "Music courses",
    services: [
      { title: "Guitar", description: "Acoustic/electric basics to songs.", priceFrom: "Rs 4,000/mo", popular: true },
      { title: "Keyboard", description: "Piano fundamentals.", priceFrom: "Rs 4,000/mo" },
      { title: "Vocals", description: "Voice training and practice.", priceFrom: "Rs 4,000/mo" },
      { title: "Kids batch", description: "Fun starter classes for children.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Song-based learning", description: "Play music you love sooner." },
      { title: "Flexible schedule", description: "Weekly slots that fit school/work." },
      { title: "Performance chance", description: "Recitals when ready." },
      { title: "All ages", description: "Kids and adults welcome." },
    ],
    faqs: [{ q: "Instrument provided?", a: "Practice instruments at academy; personal instrument recommended." }],
    galleryLabels: ["Guitar", "Keys", "Vocals", "Class"],
    trustPoints: ["Song-based", "All ages", "Weekly slots", "Recitals"],
    packages: [
      { name: "Monthly", price: "Rs 4,000", items: ["4–8 classes"] },
      { name: "Quarterly", price: "Custom", items: ["Save more"], highlighted: true },
      { name: "Private", price: "Custom", items: ["1-on-1"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Music class — instrument: ",
  }),
  dance: n({
    id: "dance",
    label: "Dance",
    family: "education",
    mapsSearches: ["dance academy"],
    tagline: "Dance academy & choreography",
    heroTitle: "Move with confidence. Join dance class.",
    heroSubtitle: "Beginner batches, wedding choreography and fitness dance sessions.",
    ctaPrimary: "Join dance batch",
    ctaSecondary: "Ask choreography",
    bookingLabel: "Enroll dance",
    servicesTitle: "Dance programs",
    services: [
      { title: "Beginner batch", description: "Fundamentals and fun routines.", priceFrom: "Rs 3,500/mo", popular: true },
      { title: "Wedding choreography", description: "Couple/family dance prep.", priceFrom: "Custom" },
      { title: "Kids dance", description: "Energetic classes for children.", priceFrom: "Custom" },
      { title: "Fitness dance", description: "Cardio dance workouts.", priceFrom: "Rs 3,000/mo" },
    ],
    features: [
      { title: "Friendly coaches", description: "Encouraging class vibe." },
      { title: "Event ready", description: "Choreography for weddings/functions." },
      { title: "All levels", description: "Start from zero." },
      { title: "Studio space", description: "Proper floor and mirrors." },
    ],
    faqs: [{ q: "Trial class?", a: "Often available — ask when messaging." }],
    galleryLabels: ["Class", "Wedding", "Kids", "Studio"],
    trustPoints: ["Beginner friendly", "Wedding choreo", "Kids batches", "Studio"],
    packages: [
      { name: "Monthly", price: "Rs 3,500", items: ["Batch"] },
      { name: "Wedding", price: "Custom", items: ["Choreo"], highlighted: true },
      { name: "Private", price: "Custom", items: ["1-on-1"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Dance class/choreography: ",
  }),
  sports: n({
    id: "sports",
    label: "Sports coaching",
    family: "education",
    mapsSearches: ["cricket coaching", "swimming"],
    tagline: "Sports coaching academy",
    heroTitle: "Train like an athlete — local coaching.",
    heroSubtitle: "Cricket, swimming and sports basics with structured practice sessions.",
    ctaPrimary: "Join coaching",
    ctaSecondary: "Ask sports offered",
    bookingLabel: "Enroll sports",
    servicesTitle: "Coaching",
    services: [
      { title: "Cricket coaching", description: "Batting, bowling, fielding drills.", priceFrom: "Custom", popular: true },
      { title: "Swimming", description: "Learn-to-swim and stroke improvement.", priceFrom: "Custom" },
      { title: "Kids academy", description: "Foundational sports for children.", priceFrom: "Custom" },
      { title: "Fitness conditioning", description: "Strength and agility for players.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Drill based", description: "Structured practice plans." },
      { title: "Age groups", description: "Kids and teens batches." },
      { title: "Match practice", description: "Game situations when ready." },
      { title: "Coach feedback", description: "Personal improvement tips." },
    ],
    faqs: [{ q: "Equipment needed?", a: "Basic kit guidance shared on enrollment." }],
    galleryLabels: ["Cricket", "Swim", "Kids", "Training"],
    trustPoints: ["Structured drills", "Age batches", "Coach feedback", "Match prep"],
    packages: [
      { name: "Monthly", price: "Custom", items: ["Batch"] },
      { name: "Quarterly", price: "Custom", items: ["Academy"], highlighted: true },
      { name: "Private", price: "Custom", items: ["1-on-1"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Sports coaching — sport/age: ",
  }),
  language: n({
    id: "language",
    label: "Language",
    family: "education",
    mapsSearches: ["spoken English"],
    tagline: "Spoken English & language classes",
    heroTitle: "Speak English with confidence.",
    heroSubtitle: "Spoken English, interview prep and beginner conversation batches.",
    ctaPrimary: "Join English class",
    ctaSecondary: "Ask batch timing",
    bookingLabel: "Enroll language",
    servicesTitle: "Language courses",
    services: [
      { title: "Spoken English", description: "Conversation-first learning.", priceFrom: "Rs 4,000/mo", popular: true },
      { title: "Interview prep", description: "Job and visa interview practice.", priceFrom: "Custom" },
      { title: "Kids English", description: "Fun speaking for children.", priceFrom: "Custom" },
      { title: "IELTS foundation", description: "Basics where offered.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Speak from day one", description: "Practice over memorization." },
      { title: "Small groups", description: "More talking time." },
      { title: "Practical topics", description: "Work, travel, daily life." },
      { title: "Flexible batches", description: "Evening options for professionals." },
    ],
    faqs: [{ q: "Beginner friendly?", a: "Yes — batches for beginners and intermediate." }],
    galleryLabels: ["Class", "Speaking", "Group", "Practice"],
    trustPoints: ["Conversation first", "Small groups", "Interview prep", "Flexible"],
    packages: [
      { name: "Monthly", price: "Rs 4,000", items: ["Batch"] },
      { name: "8-week", price: "Custom", items: ["Structured"], highlighted: true },
      { name: "Private", price: "Custom", items: ["1-on-1"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Spoken English class: ",
  }),
  "computer-classes": n({
    id: "computer-classes",
    label: "Computer classes",
    family: "education",
    mapsSearches: ["computer training institute"],
    tagline: "Computer & IT short courses",
    heroTitle: "Practical computer skills for work & study.",
    heroSubtitle: "MS Office, graphic basics, freelancing starters and short IT courses.",
    ctaPrimary: "Enroll course",
    ctaSecondary: "See course list",
    bookingLabel: "Register computer course",
    servicesTitle: "IT courses",
    services: [
      { title: "MS Office", description: "Word, Excel, PowerPoint practical.", priceFrom: "Rs 6,000", popular: true },
      { title: "Graphic basics", description: "Canva/Photoshop starter paths.", priceFrom: "Custom" },
      { title: "Freelancing start", description: "Profile and basic skill guidance.", priceFrom: "Custom" },
      { title: "Kids computing", description: "Safe beginner computer skills.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Hands-on labs", description: "Learn by doing on systems." },
      { title: "Short courses", description: "Career-oriented durations." },
      { title: "Certificate", description: "Completion certificate where offered." },
      { title: "Job-oriented", description: "Skills used in offices and freelancing." },
    ],
    faqs: [{ q: "Laptop required?", a: "Lab PCs available; personal laptop helpful." }],
    galleryLabels: ["Lab", "Excel", "Design", "Class"],
    trustPoints: ["Hands-on", "Short courses", "Certificate", "Practical"],
    packages: [
      { name: "MS Office", price: "Rs 6,000", items: ["Course"] },
      { name: "Combo", price: "Custom", items: ["Multi-skill"], highlighted: true },
      { name: "Kids", price: "Custom", items: ["Beginner"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Computer course inquiry: ",
  }),
};
