import type { NicheDefinition } from "./types";

function n(seed: NicheDefinition): NicheDefinition {
  return seed;
}

export const NICHES = {
  plumber: n({
    id: "plumber",
    label: "Plumber",
    family: "home-services",
    mapsSearches: ["plumber", "emergency plumber", "pipe repair"],
    tagline: "Fast, trusted plumbing for homes & shops",
    heroTitle: "Leak fixed. Pipe sorted. Same-day help.",
    heroSubtitle:
      "Emergency plumbing, bathroom fittings, motor & geyser work — booked in minutes on WhatsApp.",
    ctaPrimary: "Book plumber now",
    ctaSecondary: "WhatsApp estimate",
    bookingLabel: "Request a visit",
    servicesTitle: "Plumbing services",
    services: [
      { title: "Emergency leak repair", description: "Burst pipes, dripping taps, sudden blockages — we come fast.", priceFrom: "Rs 1,500", popular: true },
      { title: "Bathroom & kitchen fittings", description: "Mixers, basins, showers, WC install & replacement.", priceFrom: "Rs 2,500" },
      { title: "Motor / geyser / tank", description: "Water motor, geyser repair, overhead tank cleaning.", priceFrom: "Rs 2,000" },
      { title: "Pipe line & drainage", description: "New pipelines, drainage clearing, manhole work.", priceFrom: "Rs 3,000" },
    ],
    features: [
      { title: "Same-day visits", description: "Most Bahria / Valencia / Township calls handled same day." },
      { title: "Transparent pricing", description: "Estimate on WhatsApp before we start — no surprise bills." },
      { title: "Genuine parts", description: "Quality fittings and spare parts with workmanship care." },
      { title: "Clean finish", description: "We protect floors and leave the area tidy after the job." },
    ],
    faqs: [
      { q: "Do you offer emergency plumbing?", a: "Yes — message on WhatsApp with your area and issue. We prioritize burst pipes and major leaks." },
      { q: "How is pricing decided?", a: "We share an estimate after a short description or on-site check. Parts are billed separately if needed." },
      { q: "Which areas do you cover?", a: "We cover the listed city/area and nearby societies. Confirm coverage in chat before booking." },
    ],
    galleryLabels: ["Bathroom fitting", "Pipe repair", "Geyser work", "Drainage clear"],
    trustPoints: ["Licensed technicians", "Same-day slots", "WhatsApp updates", "Workmanship care"],
    packages: [
      { name: "Visit & fix", price: "Rs 1,500+", items: ["Site visit", "Basic repair", "WhatsApp updates"] },
      { name: "Full bathroom", price: "Custom", items: ["Fittings", "Piping", "Testing", "Cleanup"], highlighted: true },
      { name: "AMC (monthly)", price: "Rs 4,999", period: "/mo", items: ["2 visits", "Priority support", "Discounted parts"] },
    ],
    specialSections: ["emergency", "booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! I need a plumber visit. Please share availability.",
  }),

  electrician: n({
    id: "electrician",
    label: "Electrician",
    family: "home-services",
    mapsSearches: ["electrician", "wiring", "electrical contractor"],
    tagline: "Safe wiring & electrical fixes for homes",
    heroTitle: "Power issues fixed — safely and on time.",
    heroSubtitle: "Wiring, DB boards, fans, lights, generators & UPS setup with clean finishing.",
    ctaPrimary: "Book electrician",
    ctaSecondary: "Send fault details",
    bookingLabel: "Schedule electrical visit",
    servicesTitle: "Electrical services",
    services: [
      { title: "House wiring & DB", description: "New wiring, board upgrade, MCB / ELCB install.", priceFrom: "Rs 2,500", popular: true },
      { title: "Fan, light & switch", description: "Installation, repair, chandelier and LED work.", priceFrom: "Rs 800" },
      { title: "Generator / UPS", description: "Changeover, wiring, battery points, load check.", priceFrom: "Rs 3,000" },
      { title: "Short circuit & fault finding", description: "Diagnose trips, sparks, hot switches safely.", priceFrom: "Rs 1,500" },
    ],
    features: [
      { title: "Safety first", description: "Proper earthing checks and load-safe recommendations." },
      { title: "Neat cabling", description: "Hidden/clean routing where possible — no messy finish." },
      { title: "Parts guidance", description: "We advise genuine switches, breakers and wires." },
      { title: "Quick response", description: "Priority for power-cut and sparking emergencies." },
    ],
    faqs: [
      { q: "Can you handle commercial shops?", a: "Yes — shops, offices and small commercial units depending on load and area." },
      { q: "Do you supply materials?", a: "We can bring materials or use your preferred brand. Estimate shared first." },
    ],
    galleryLabels: ["DB board", "LED install", "Wiring", "UPS setup"],
    trustPoints: ["Safety tested", "Clean finish", "Genuine parts advice", "Fast response"],
    packages: [
      { name: "Fault visit", price: "Rs 1,500+", items: ["Diagnosis", "Basic fix", "Safety tips"] },
      { name: "Full room wiring", price: "Custom", items: ["Wiring", "Points", "Switches", "Testing"], highlighted: true },
      { name: "Shop package", price: "Custom", items: ["Load plan", "DB", "Lights", "Sign wiring"] },
    ],
    specialSections: ["emergency", "booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! I need an electrician. Issue: ",
  }),

  "ac-hvac": n({
    id: "ac-hvac",
    label: "AC / HVAC",
    family: "home-services",
    mapsSearches: ["AC repair", "HVAC", "air conditioning service"],
    tagline: "AC install, gas & deep cleaning",
    heroTitle: "Cool air back — install, gas, service.",
    heroSubtitle: "Split AC install, gas refill, deep cleaning and copper work with same-day slots.",
    ctaPrimary: "Book AC service",
    ctaSecondary: "WhatsApp model & issue",
    bookingLabel: "Book AC technician",
    servicesTitle: "AC services",
    services: [
      { title: "AC installation", description: "Indoor/outdoor unit, copper, drainage, vacuum.", priceFrom: "Rs 4,500", popular: true },
      { title: "Gas refill & leak", description: "Leak detection, pressure check, gas top-up.", priceFrom: "Rs 3,500" },
      { title: "Deep cleaning", description: "Jet wash, filter clean, coil service for better cooling.", priceFrom: "Rs 2,500" },
      { title: "Repair & PCB", description: "Not cooling, water dripping, remote/PCB issues.", priceFrom: "Rs 2,000" },
    ],
    features: [
      { title: "Brand-aware techs", description: "Experience with common split AC brands in Pakistan." },
      { title: "Cooling guarantee", description: "We verify temperature drop before leaving." },
      { title: "Season ready", description: "Pre-summer service packages for homes and offices." },
      { title: "Neat copper work", description: "Proper insulation and tidy outdoor placement." },
    ],
    faqs: [
      { q: "Do you do inverter ACs?", a: "Yes — install and service for inverter and non-inverter splits." },
      { q: "How long does deep clean take?", a: "Usually 60–90 minutes per unit depending on access." },
    ],
    galleryLabels: ["Install", "Deep clean", "Outdoor unit", "Gas work"],
    trustPoints: ["Same-day service", "Cooling verified", "Parts available", "Home & shop"],
    packages: [
      { name: "Service", price: "Rs 2,500", items: ["Deep clean", "Filter", "Check gas"] },
      { name: "Install", price: "Rs 4,500+", items: ["Mount", "Copper", "Vacuum", "Test"], highlighted: true },
      { name: "Season pack (2 AC)", price: "Rs 4,500", items: ["2 deep cleans", "Priority booking"] },
    ],
    specialSections: ["booking", "warranty", "emergency"],
    whatsappPreset: "Assalam o Alaikum! AC service needed. Brand/model: ",
  }),

  carpenter: n({
    id: "carpenter",
    label: "Carpenter",
    family: "home-services",
    mapsSearches: ["carpenter", "furniture repair", "woodwork"],
    tagline: "Custom woodwork & furniture repair",
    heroTitle: "Furniture fixed. Cabinets built. On site.",
    heroSubtitle: "Door repair, wardrobes, kitchen cabinets and custom woodwork for homes.",
    ctaPrimary: "Get woodwork quote",
    ctaSecondary: "Send photo on WhatsApp",
    bookingLabel: "Book carpenter visit",
    servicesTitle: "Carpentry services",
    services: [
      { title: "Furniture repair", description: "Chairs, beds, tables, hinges and polish touch-ups.", priceFrom: "Rs 1,500", popular: true },
      { title: "Doors & frames", description: "Door install, lock fitting, frame repair.", priceFrom: "Rs 2,500" },
      { title: "Wardrobe / cabinets", description: "Custom storage, kitchen cabinets, TV units.", priceFrom: "Custom" },
      { title: "Shelves & fixtures", description: "Wall shelves, shoe racks, partition work.", priceFrom: "Rs 2,000" },
    ],
    features: [
      { title: "On-site measurement", description: "Accurate measure before cutting and install." },
      { title: "Material options", description: "MDF, laminate, solid wood — choose your budget." },
      { title: "Clean install", description: "Dust control and tidy finishing in living spaces." },
      { title: "Photo quotes", description: "Send photos for a faster estimate." },
    ],
    faqs: [
      { q: "Can you match existing furniture color?", a: "We try to match polish/laminate as closely as possible." },
    ],
    galleryLabels: ["Wardrobe", "Kitchen", "Door", "Repair"],
    trustPoints: ["Custom measure", "Neat finish", "Photo estimate", "Home visit"],
    packages: [
      { name: "Repair visit", price: "Rs 1,500+", items: ["Inspect", "Fix", "Adjust"] },
      { name: "Custom unit", price: "Custom", items: ["Design", "Material", "Install"], highlighted: true },
      { name: "Kitchen cabinets", price: "Custom", items: ["Measure", "Build", "Fit"] },
    ],
    specialSections: ["booking", "before-after", "portfolio"],
    whatsappPreset: "Assalam o Alaikum! Carpenter needed. Work: ",
  }),

  painter: n({
    id: "painter",
    label: "Painter",
    family: "home-services",
    mapsSearches: ["house painter", "painting contractor"],
    tagline: "Interior & exterior painting",
    heroTitle: "Fresh walls. Clean lines. Fair quote.",
    heroSubtitle: "Room painting, putty, weather shield and texture finishes for homes and shops.",
    ctaPrimary: "Get paint quote",
    ctaSecondary: "Share room size",
    bookingLabel: "Book painting survey",
    servicesTitle: "Painting services",
    services: [
      { title: "Interior painting", description: "Rooms, putty, emulsion, masking and cleanup.", priceFrom: "Rs 18/sq ft", popular: true },
      { title: "Exterior / weather shield", description: "Outer walls with durable weather coating.", priceFrom: "Rs 22/sq ft" },
      { title: "Texture & design", description: "Feature walls, texture, stencil accents.", priceFrom: "Custom" },
      { title: "Shop / office makeover", description: "Fast commercial painting with minimal downtime.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Surface prep", description: "Proper putty and sanding for a lasting finish." },
      { title: "Brand paints", description: "Work with Berger, Nippon, Brighto and more." },
      { title: "Furniture cover", description: "We cover floors and furniture before painting." },
      { title: "Sq ft clarity", description: "Transparent measurement and quote." },
    ],
    faqs: [{ q: "How long for one room?", a: "Typically 1–2 days including prep and drying time." }],
    galleryLabels: ["Living room", "Exterior", "Texture", "Shop"],
    trustPoints: ["Sq ft quote", "Brand paints", "Clean site", "On-time finish"],
    packages: [
      { name: "Single room", price: "From Rs 12,000", items: ["Prep", "2 coats", "Cleanup"] },
      { name: "Full house", price: "Custom", items: ["Survey", "Putty", "Paint", "Touch-up"], highlighted: true },
      { name: "Shop front", price: "Custom", items: ["Fast turnaround", "Bold finish"] },
    ],
    specialSections: ["before-after", "booking", "portfolio"],
    whatsappPreset: "Assalam o Alaikum! Need painting. Area/size: ",
  }),

  roofer: n({
    id: "roofer",
    label: "Roofer",
    family: "home-services",
    mapsSearches: ["roofing", "roof repair"],
    tagline: "Roof leak repair & waterproofing",
    heroTitle: "Stop roof leaks before the next rain.",
    heroSubtitle: "Sheet work, waterproofing, heat-proof coating and emergency leak fixes.",
    ctaPrimary: "Book roof check",
    ctaSecondary: "Send leak photos",
    bookingLabel: "Schedule roof inspection",
    servicesTitle: "Roofing services",
    services: [
      { title: "Leak repair", description: "Find and seal leaks on terrace and sheets.", priceFrom: "Rs 3,000", popular: true },
      { title: "Waterproofing", description: "Chemical / membrane waterproofing for terraces.", priceFrom: "Custom" },
      { title: "Heat-proof coating", description: "Reduce heat and protect surface.", priceFrom: "Custom" },
      { title: "Sheet / shade work", description: "GI sheets, sheds and rain water management.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Rain-ready", description: "Priority slots before monsoon season." },
      { title: "Photo diagnosis", description: "Share photos for faster quotes." },
      { title: "Warranty options", description: "Waterproofing packages with service window." },
      { title: "Safety on height", description: "Experienced team for terrace work." },
    ],
    faqs: [{ q: "Can you fix during light rain?", a: "Emergency sealing yes; full waterproofing needs dry weather." }],
    galleryLabels: ["Leak seal", "Terrace", "Sheet roof", "Coating"],
    trustPoints: ["Leak experts", "Monsoon ready", "Warranty options", "Photo quote"],
    packages: [
      { name: "Emergency seal", price: "Rs 3,000+", items: ["Inspect", "Seal", "Advice"] },
      { name: "Full waterproof", price: "Custom", items: ["Prep", "Coat", "Test"], highlighted: true },
      { name: "Heat coat", price: "Custom", items: ["Clean", "Coat", "Finish"] },
    ],
    specialSections: ["emergency", "warranty", "booking"],
    whatsappPreset: "Assalam o Alaikum! Roof leak/repair needed. Details: ",
  }),

  handyman: n({
    id: "handyman",
    label: "Handyman",
    family: "home-services",
    mapsSearches: ["handyman", "home repair"],
    tagline: "One call for small home fixes",
    heroTitle: "Small repairs. Big relief. One visit.",
    heroSubtitle: "Door handles, shelves, minor plumbing/electrical and assembly — done right.",
    ctaPrimary: "Book handyman",
    ctaSecondary: "List your tasks",
    bookingLabel: "Book multi-fix visit",
    servicesTitle: "Handyman tasks",
    services: [
      { title: "Multi-fix visit", description: "Several small jobs completed in one appointment.", priceFrom: "Rs 2,000", popular: true },
      { title: "Mounting & assembly", description: "TV mounts, shelves, furniture assembly.", priceFrom: "Rs 1,500" },
      { title: "Door & lock fixes", description: "Handles, hinges, simple lock issues.", priceFrom: "Rs 1,200" },
      { title: "Minor home repair", description: "Small plumbing/electrical touch-ups.", priceFrom: "Rs 1,500" },
    ],
    features: [
      { title: "Task list friendly", description: "Send a checklist — we plan one efficient visit." },
      { title: "Tool-ready", description: "Common tools brought to site." },
      { title: "Honest scope", description: "We tell you if a specialist is needed." },
      { title: "Apartment friendly", description: "Quiet, careful work in flats and societies." },
    ],
    faqs: [{ q: "Minimum visit charge?", a: "Shared upfront based on area and task list." }],
    galleryLabels: ["Mounting", "Door fix", "Assembly", "Shelf"],
    trustPoints: ["Multi-fix", "Careful work", "Clear pricing", "Society friendly"],
    packages: [
      { name: "1-hour fix", price: "Rs 2,000", items: ["Up to 2 small tasks"] },
      { name: "Half-day", price: "Rs 5,500", items: ["Multiple tasks", "Priority"], highlighted: true },
      { name: "Move-in checklist", price: "Custom", items: ["Fixes after shifting"] },
    ],
    specialSections: ["booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! Handyman tasks: ",
  }),

  cleaning: n({
    id: "cleaning",
    label: "Cleaning",
    family: "home-services",
    mapsSearches: ["house cleaning", "office cleaning", "deep cleaning"],
    tagline: "Deep cleaning for home & office",
    heroTitle: "Spotless spaces. Trained team. Fixed packages.",
    heroSubtitle: "Sofa, kitchen, bathroom and full-home deep cleaning with eco-safe products.",
    ctaPrimary: "Book cleaning",
    ctaSecondary: "See packages",
    bookingLabel: "Schedule cleaning",
    servicesTitle: "Cleaning packages",
    services: [
      { title: "Home deep clean", description: "Kitchen, baths, floors, dusting end-to-end.", priceFrom: "Rs 6,000", popular: true },
      { title: "Sofa / carpet", description: "Shampoo and stain treatment for sofas and carpets.", priceFrom: "Rs 2,500" },
      { title: "Office cleaning", description: "Desks, floors, washrooms — after-hours available.", priceFrom: "Custom" },
      { title: "Move-in / move-out", description: "Empty home deep clean before or after shifting.", priceFrom: "Rs 8,000" },
    ],
    features: [
      { title: "Trained staff", description: "Uniformed team with checklist-based cleaning." },
      { title: "Own equipment", description: "Machines and chemicals brought by us." },
      { title: "Before/after photos", description: "Optional proof of work for offices." },
      { title: "Flexible timing", description: "Morning, evening and weekend slots." },
    ],
    faqs: [{ q: "Do I provide materials?", a: "No — we bring cleaning chemicals and tools." }],
    galleryLabels: ["Kitchen", "Sofa", "Bathroom", "Office"],
    trustPoints: ["Checklist clean", "Own equipment", "Background-aware hiring", "Fixed packages"],
    packages: [
      { name: "1 BHK", price: "Rs 6,000", items: ["Deep clean", "Baths", "Kitchen"] },
      { name: "2–3 BHK", price: "Rs 9,500", items: ["Full home", "Kitchen heavy"], highlighted: true },
      { name: "Sofa 5-seater", price: "Rs 3,500", items: ["Shampoo", "Dry"] },
    ],
    specialSections: ["booking", "before-after"],
    whatsappPreset: "Assalam o Alaikum! Cleaning needed for: ",
  }),

  "pest-control": n({
    id: "pest-control",
    label: "Pest control",
    family: "home-services",
    mapsSearches: ["pest control", "termite", "cockroach control"],
    tagline: "Cockroach, termite & mosquito control",
    heroTitle: "Pests out. Family safe. Treated right.",
    heroSubtitle: "Cockroach, termite, bed bug and mosquito treatment for homes and shops.",
    ctaPrimary: "Book pest treatment",
    ctaSecondary: "Describe the pest",
    bookingLabel: "Book pest visit",
    servicesTitle: "Pest treatments",
    services: [
      { title: "Cockroach gel / spray", description: "Kitchen and drain focused treatment.", priceFrom: "Rs 3,500", popular: true },
      { title: "Termite control", description: "Wood and soil treatment with follow-up plan.", priceFrom: "Custom" },
      { title: "Bed bug treatment", description: "Mattress and furniture focused process.", priceFrom: "Rs 5,000" },
      { title: "Mosquito / fogging", description: "Outdoor and society fogging options.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Child & pet caution", description: "We brief safety timings after treatment." },
      { title: "Follow-up visits", description: "Packages include revisit where needed." },
      { title: "Shop friendly", description: "After-hours treatment for restaurants and stores." },
      { title: "Licensed chemicals", description: "Approved formulations used by trained staff." },
    ],
    faqs: [{ q: "How soon can we use kitchen?", a: "We share exact wait time based on treatment type." }],
    galleryLabels: ["Kitchen gel", "Termite", "Fogging", "Shop"],
    trustPoints: ["Safe process", "Follow-ups", "Home & shop", "Trained team"],
    packages: [
      { name: "Cockroach", price: "Rs 3,500", items: ["Treatment", "Tips"] },
      { name: "Termite", price: "Custom", items: ["Inspect", "Treat", "Follow-up"], highlighted: true },
      { name: "Annual AMC", price: "Custom", items: ["Quarterly visits"] },
    ],
    specialSections: ["booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! Pest control for: ",
  }),

  "water-tank": n({
    id: "water-tank",
    label: "Water / tank / boring",
    family: "home-services",
    mapsSearches: ["water tank cleaning", "boring", "RO service"],
    tagline: "Tank cleaning, boring & RO service",
    heroTitle: "Clean water starts with a clean tank.",
    heroSubtitle: "Overhead tank cleaning, boring support and RO filter service for homes.",
    ctaPrimary: "Book tank cleaning",
    ctaSecondary: "Ask about boring",
    bookingLabel: "Book water service",
    servicesTitle: "Water services",
    services: [
      { title: "Tank cleaning", description: "Empty, scrub, disinfectant and refill guidance.", priceFrom: "Rs 2,500", popular: true },
      { title: "RO service", description: "Filter change, flush and taste/pressure check.", priceFrom: "Rs 1,500" },
      { title: "Motor / boring support", description: "Motor install and boring coordination.", priceFrom: "Custom" },
      { title: "Underground tank", description: "Larger tank cleaning with proper safety.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Hygienic process", description: "Disinfectant and rinse steps included." },
      { title: "Before/after", description: "Optional photos of tank condition." },
      { title: "Society experience", description: "Familiar with Bahria / DHA access rules." },
      { title: "RO brands", description: "Common local RO systems supported." },
    ],
    faqs: [{ q: "How often to clean tank?", a: "Every 3–6 months is typical for overhead tanks." }],
    galleryLabels: ["Tank clean", "RO", "Motor", "Underground"],
    trustPoints: ["Hygienic", "Photo proof", "Society ready", "RO + tank"],
    packages: [
      { name: "Overhead tank", price: "Rs 2,500", items: ["Clean", "Disinfect"] },
      { name: "Tank + RO", price: "Rs 3,800", items: ["Both services"], highlighted: true },
      { name: "Society contract", price: "Custom", items: ["Multiple tanks"] },
    ],
    specialSections: ["booking", "before-after"],
    whatsappPreset: "Assalam o Alaikum! Tank/RO service needed: ",
  }),

  solar: n({
    id: "solar",
    label: "Solar",
    family: "home-services",
    mapsSearches: ["solar panel installation"],
    tagline: "Solar survey, install & net metering help",
    heroTitle: "Cut electricity bills with solar done right.",
    heroSubtitle: "Site survey, panel install, inverter setup and guidance for net metering.",
    ctaPrimary: "Book solar survey",
    ctaSecondary: "Share bill units",
    bookingLabel: "Request solar survey",
    servicesTitle: "Solar services",
    services: [
      { title: "Free survey", description: "Roof check, shade analysis, system size advice.", priceFrom: "Free", popular: true },
      { title: "On-grid install", description: "Panels, inverter, structure and commissioning.", priceFrom: "Custom" },
      { title: "Hybrid / battery", description: "Backup-focused systems for load shedding.", priceFrom: "Custom" },
      { title: "Maintenance", description: "Cleaning, checkup and performance review.", priceFrom: "Rs 5,000" },
    ],
    features: [
      { title: "Bill-based sizing", description: "System recommended from your unit usage." },
      { title: "Brand options", description: "Tier-1 panels and trusted inverters." },
      { title: "Documentation help", description: "Support for paperwork where applicable." },
      { title: "After-sales", description: "Service contacts after install." },
    ],
    faqs: [{ q: "How long for install?", a: "Typically a few days after survey and material readiness." }],
    galleryLabels: ["Roof install", "Inverter", "Structure", "Monitoring"],
    trustPoints: ["Survey first", "Bill savings focus", "Quality hardware", "After-sales"],
    packages: [
      { name: "5 kW", price: "Custom", items: ["Survey", "Install", "Test"] },
      { name: "10 kW", price: "Custom", items: ["Full system"], highlighted: true },
      { name: "Maintenance", price: "Rs 5,000", items: ["Clean", "Check"] },
    ],
    specialSections: ["consultation", "booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! Solar survey please. Monthly units: ",
  }),

  cctv: n({
    id: "cctv",
    label: "CCTV / security",
    family: "home-services",
    mapsSearches: ["CCTV installation", "security cameras"],
    tagline: "CCTV install & remote mobile view",
    heroTitle: "See your shop & home from your phone.",
    heroSubtitle: "Camera install, DVR/NVR setup, wiring and mobile app configuration.",
    ctaPrimary: "Book CCTV install",
    ctaSecondary: "Ask camera plan",
    bookingLabel: "Book security survey",
    servicesTitle: "CCTV services",
    services: [
      { title: "4 camera package", description: "Indoor/outdoor mix with app viewing.", priceFrom: "Custom", popular: true },
      { title: "Shop security", description: "Entrance, counter and godown coverage.", priceFrom: "Custom" },
      { title: "Service & repair", description: "No video, night vision, HDD and cable faults.", priceFrom: "Rs 2,000" },
      { title: "Remote setup", description: "Phone app, user sharing and alerts.", priceFrom: "Rs 1,500" },
    ],
    features: [
      { title: "Coverage planning", description: "We map blind spots before install." },
      { title: "Night vision", description: "Proper camera placement for dark areas." },
      { title: "Mobile access", description: "Watch live from Android/iOS." },
      { title: "Shop specialty", description: "Retail and warehouse layouts understood." },
    ],
    faqs: [{ q: "Do you provide cameras?", a: "Yes — or we can install your purchased kit." }],
    galleryLabels: ["Shop cam", "App view", "Wiring", "NVR"],
    trustPoints: ["Mobile view", "Blind-spot plan", "Shop ready", "After support"],
    packages: [
      { name: "4 cam", price: "Custom", items: ["Cameras", "DVR", "App"] },
      { name: "8 cam", price: "Custom", items: ["Full coverage"], highlighted: true },
      { name: "Service visit", price: "Rs 2,000", items: ["Diagnose", "Fix"] },
    ],
    specialSections: ["booking", "warranty", "consultation"],
    whatsappPreset: "Assalam o Alaikum! CCTV install/service needed: ",
  }),

  locksmith: n({
    id: "locksmith",
    label: "Locksmith",
    family: "home-services",
    mapsSearches: ["locksmith", "key maker"],
    tagline: "Lock open, key copy & digital locks",
    heroTitle: "Locked out? Keys & locks sorted fast.",
    heroSubtitle: "Emergency door opening, key cutting, lock change and digital lock install.",
    ctaPrimary: "Call locksmith",
    ctaSecondary: "WhatsApp location",
    bookingLabel: "Request locksmith",
    servicesTitle: "Locksmith services",
    services: [
      { title: "Emergency unlock", description: "Car/home/shop door opening with care.", priceFrom: "Rs 2,000", popular: true },
      { title: "Lock change", description: "Replace worn or unsafe locks.", priceFrom: "Rs 1,500" },
      { title: "Key copy", description: "Duplicate keys for home and cabinets.", priceFrom: "Rs 300" },
      { title: "Digital lock install", description: "Password/fingerprint locks for modern homes.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Damage-aware", description: "We open with minimal door damage when possible." },
      { title: "Fast response", description: "Priority for lockout emergencies." },
      { title: "Security upgrade", description: "Recommend stronger locks when needed." },
      { title: "Shop shutters", description: "Shutter and padlock support available." },
    ],
    faqs: [{ q: "Proof of ownership?", a: "For security we may ask basic verification on site." }],
    galleryLabels: ["Unlock", "Key copy", "Digital lock", "Shutter"],
    trustPoints: ["Emergency ready", "Careful open", "Key & lock", "Digital options"],
    packages: [
      { name: "Unlock", price: "Rs 2,000+", items: ["Emergency open"] },
      { name: "Lock replace", price: "Rs 1,500+", items: ["New lock", "Keys"], highlighted: true },
      { name: "Digital lock", price: "Custom", items: ["Device", "Install"] },
    ],
    specialSections: ["emergency", "booking"],
    whatsappPreset: "Assalam o Alaikum! Locksmith needed at: ",
  }),

  moving: n({
    id: "moving",
    label: "Moving / packers",
    family: "home-services",
    mapsSearches: ["packers and movers"],
    tagline: "Packers & movers for home shift",
    heroTitle: "Shift home without the headache.",
    heroSubtitle: "Packing, loading, transport and unpacking for flats and houses across the city.",
    ctaPrimary: "Get shifting quote",
    ctaSecondary: "Share inventory",
    bookingLabel: "Book movers",
    servicesTitle: "Moving services",
    services: [
      { title: "Home shifting", description: "Full pack, move and unpack for apartments.", priceFrom: "Custom", popular: true },
      { title: "Office relocation", description: "Desks, IT gear and weekend moves.", priceFrom: "Custom" },
      { title: "Packing only", description: "Professional packing materials and labor.", priceFrom: "Rs 8,000" },
      { title: "Vehicle + labor", description: "Suzuki/Mazda with helpers for local moves.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Inventory list", description: "Item checklist to avoid surprises." },
      { title: "Careful handling", description: "Fragile marking and protected loading." },
      { title: "Same-city & intercity", description: "Local and longer routes available." },
      { title: "Transparent quote", description: "Price based on volume and floors." },
    ],
    faqs: [{ q: "Do you dismantle furniture?", a: "Yes — beds and wardrobes can be dismantled/reassembled on request." }],
    galleryLabels: ["Packing", "Loading", "Truck", "Unpack"],
    trustPoints: ["Inventory based", "Fragile care", "Helper team", "Clear quote"],
    packages: [
      { name: "Studio / 1BHK", price: "Custom", items: ["Pack", "Move"] },
      { name: "2–3 BHK", price: "Custom", items: ["Full service"], highlighted: true },
      { name: "Office", price: "Custom", items: ["Weekend slot"] },
    ],
    specialSections: ["booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! Moving quote needed from/to: ",
  }),

  interior: n({
    id: "interior",
    label: "Interior",
    family: "home-services",
    mapsSearches: ["interior designer", "modular kitchen"],
    tagline: "Modular kitchen & interior design",
    heroTitle: "Spaces designed for how you live.",
    heroSubtitle: "Modular kitchens, wardrobes, TV units and full-room interior planning.",
    ctaPrimary: "Book design consult",
    ctaSecondary: "Send room photos",
    bookingLabel: "Book interior consult",
    servicesTitle: "Interior services",
    services: [
      { title: "Modular kitchen", description: "Layout, materials, appliances cutouts, install.", priceFrom: "Custom", popular: true },
      { title: "Wardrobe design", description: "Sliding/hinged storage optimized for space.", priceFrom: "Custom" },
      { title: "Living makeover", description: "TV unit, feature wall, lighting plan.", priceFrom: "Custom" },
      { title: "3D concept", description: "Visualize before fabrication.", priceFrom: "Rs 15,000" },
    ],
    features: [
      { title: "Measure & plan", description: "On-site measure with layout proposal." },
      { title: "Material choices", description: "Budget to premium laminate options." },
      { title: "End-to-end", description: "Design to installation coordination." },
      { title: "Pakistan homes", description: "Layouts suited to local apartment sizes." },
    ],
    faqs: [{ q: "Do you only design or also build?", a: "We can do design-only or full execution with partners." }],
    galleryLabels: ["Kitchen", "Wardrobe", "Living", "3D"],
    trustPoints: ["3D option", "Modular focus", "Local layouts", "Install partners"],
    packages: [
      { name: "Consult", price: "Rs 5,000", items: ["Visit", "Ideas"] },
      { name: "Kitchen project", price: "Custom", items: ["Design", "Build"], highlighted: true },
      { name: "Full home", price: "Custom", items: ["Multi-room"] },
    ],
    specialSections: ["portfolio", "consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Interior consult — space: ",
  }),
} as const satisfies Record<string, NicheDefinition>;
