import type { NicheDefinition } from "./types";

const n = (s: NicheDefinition) => s;

export const NICHES_HEALTH: Record<string, NicheDefinition> = {
  dentist: n({
    id: "dentist",
    label: "Dentist",
    family: "health",
    mapsSearches: ["dentist", "dental clinic"],
    tagline: "Dental clinic for family care",
    heroTitle: "Healthy smile. Gentle dental care.",
    heroSubtitle: "Cleaning, fillings, braces consult and teeth whitening — easy appointment booking.",
    ctaPrimary: "Book dental visit",
    ctaSecondary: "Ask about pain visit",
    bookingLabel: "Book dentist",
    servicesTitle: "Dental services",
    services: [
      { title: "Cleaning & polishing", description: "Scaling for healthier gums.", priceFrom: "Rs 3,000", popular: true },
      { title: "Filling", description: "Cavity treatment with quality materials.", priceFrom: "Rs 2,500" },
      { title: "Root canal", description: "RCT with follow-up crown guidance.", priceFrom: "Custom" },
      { title: "Braces consult", description: "Alignment assessment and plan.", priceFrom: "Rs 2,000" },
    ],
    features: [
      { title: "Gentle care", description: "Patient-friendly approach for kids and adults." },
      { title: "Sterilized tools", description: "Strict clinic sterilization." },
      { title: "Treatment plan", description: "Clear steps and cost before starting." },
      { title: "Emergency slots", description: "Priority for severe tooth pain." },
    ],
    faqs: [{ q: "Do you take walk-ins for pain?", a: "Yes when slots allow — message for fastest time." }],
    galleryLabels: ["Clinic", "Cleaning", "Kids", "Smile"],
    trustPoints: ["Sterile", "Family dental", "Clear plans", "Pain priority"],
    packages: [
      { name: "Cleaning", price: "Rs 3,000", items: ["Scale & polish"] },
      { name: "Smile plan", price: "Custom", items: ["Consult + treatment"], highlighted: true },
      { name: "Kids visit", price: "Rs 2,000+", items: ["Checkup"] },
    ],
    specialSections: ["booking", "consultation", "emergency"],
    whatsappPreset: "Assalam o Alaikum! Dental appointment for: ",
  }),
  physiotherapy: n({
    id: "physiotherapy",
    label: "Physiotherapy",
    family: "health",
    mapsSearches: ["physiotherapist"],
    tagline: "Physio for pain relief & recovery",
    heroTitle: "Move better. Hurt less. Recover stronger.",
    heroSubtitle: "Back pain, sports injury, posture and post-surgery physiotherapy sessions.",
    ctaPrimary: "Book physio session",
    ctaSecondary: "Describe pain area",
    bookingLabel: "Book physiotherapy",
    servicesTitle: "Physio services",
    services: [
      { title: "Assessment", description: "Movement and pain assessment.", priceFrom: "Rs 2,000", popular: true },
      { title: "Back & neck", description: "Desk-job and disc-related care.", priceFrom: "Rs 2,500" },
      { title: "Sports injury", description: "Rehab plans for athletes.", priceFrom: "Custom" },
      { title: "Home physio", description: "Selected area home sessions.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Personalized plan", description: "Exercises matched to your condition." },
      { title: "Progress tracking", description: "Session goals and follow-ups." },
      { title: "Home option", description: "For limited mobility patients." },
      { title: "Education", description: "Learn posture habits that last." },
    ],
    faqs: [{ q: "How many sessions?", a: "Depends on condition — plan shared after assessment." }],
    galleryLabels: ["Assessment", "Exercise", "Therapy", "Rehab"],
    trustPoints: ["Assessment first", "Home option", "Sports rehab", "Clear plans"],
    packages: [
      { name: "Assessment", price: "Rs 2,000", items: ["Eval"] },
      { name: "5 sessions", price: "Custom", items: ["Plan + therapy"], highlighted: true },
      { name: "Home pack", price: "Custom", items: ["Visits"] },
    ],
    specialSections: ["booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! Physio needed for: ",
  }),
  gym: n({
    id: "gym",
    label: "Gym",
    family: "health",
    mapsSearches: ["gym", "fitness center"],
    tagline: "Gym membership & personal training",
    heroTitle: "Train hard. Join a gym that shows up for you.",
    heroSubtitle: "Strength, cardio, PT sessions and flexible memberships for men and women.",
    ctaPrimary: "Join / trial",
    ctaSecondary: "Ask fees",
    bookingLabel: "Book gym trial",
    servicesTitle: "Memberships",
    services: [
      { title: "Monthly membership", description: "Full gym access.", priceFrom: "Rs 4,000", popular: true },
      { title: "Personal training", description: "1-on-1 coaching sessions.", priceFrom: "Rs 15,000" },
      { title: "Ladies timing", description: "Dedicated hours where available.", priceFrom: "Custom" },
      { title: "Trial day", description: "Try equipment and coaches.", priceFrom: "Free/Paid" },
    ],
    features: [
      { title: "Coached form", description: "Learn safe lifting basics." },
      { title: "Clean floor", description: "Maintained equipment and hygiene." },
      { title: "Flexible plans", description: "Monthly and quarterly options." },
      { title: "Progress focus", description: "PT plans for fat loss / muscle." },
    ],
    faqs: [{ q: "Is there a trial?", a: "Yes — message to book a trial slot." }],
    galleryLabels: ["Weights", "Cardio", "PT", "Floor"],
    trustPoints: ["PT available", "Clean gym", "Flexible fees", "Trial welcome"],
    packages: [
      { name: "Monthly", price: "Rs 4,000", items: ["Access"] },
      { name: "Quarterly", price: "Custom", items: ["Save more"], highlighted: true },
      { name: "PT add-on", price: "Custom", items: ["12 sessions"] },
    ],
    specialSections: ["booking", "classes"],
    whatsappPreset: "Assalam o Alaikum! Gym membership/trial: ",
  }),
  yoga: n({
    id: "yoga",
    label: "Yoga",
    family: "health",
    mapsSearches: ["yoga studio"],
    tagline: "Yoga classes for all levels",
    heroTitle: "Breathe better. Move gently. Feel lighter.",
    heroSubtitle: "Group yoga, beginners batches and private sessions for flexibility and calm.",
    ctaPrimary: "Join a class",
    ctaSecondary: "Ask batch timings",
    bookingLabel: "Book yoga class",
    servicesTitle: "Yoga offerings",
    services: [
      { title: "Group class", description: "Beginner-friendly group sessions.", priceFrom: "Rs 1,500", popular: true },
      { title: "Monthly batch", description: "Regular weekly classes.", priceFrom: "Rs 5,000" },
      { title: "Private session", description: "1-on-1 personalized practice.", priceFrom: "Rs 3,000" },
      { title: "Corporate / ladies", description: "Special group batches.", priceFrom: "Custom" },
    ],
    features: [
      { title: "All levels", description: "Modifications for beginners." },
      { title: "Calm space", description: "Clean mats and peaceful room." },
      { title: "Breath + mobility", description: "More than just stretching." },
      { title: "Flexible batches", description: "Morning and evening options." },
    ],
    faqs: [{ q: "Do I bring a mat?", a: "Mats available; personal mat welcome." }],
    galleryLabels: ["Class", "Pose", "Studio", "Breath"],
    trustPoints: ["Beginner friendly", "Private option", "Calm studio", "Batch timings"],
    packages: [
      { name: "Drop-in", price: "Rs 1,500", items: ["1 class"] },
      { name: "Monthly", price: "Rs 5,000", items: ["Batch"], highlighted: true },
      { name: "Private 4x", price: "Custom", items: ["1-on-1"] },
    ],
    specialSections: ["classes", "booking"],
    whatsappPreset: "Assalam o Alaikum! Yoga class inquiry: ",
  }),
  clinic: n({
    id: "clinic",
    label: "Clinic",
    family: "health",
    mapsSearches: ["general physician clinic"],
    tagline: "GP clinic for family health",
    heroTitle: "Family clinic care when you need it.",
    heroSubtitle: "General physician consults, follow-ups and basic checks — book on WhatsApp.",
    ctaPrimary: "Book appointment",
    ctaSecondary: "Ask doctor timing",
    bookingLabel: "Book clinic visit",
    servicesTitle: "Clinic services",
    services: [
      { title: "GP consult", description: "General checkup and advice.", priceFrom: "Rs 1,500", popular: true },
      { title: "Follow-up", description: "Review after treatment.", priceFrom: "Rs 1,000" },
      { title: "Family visit", description: "Multiple family members slots.", priceFrom: "Custom" },
      { title: "Basic checks", description: "BP / sugar checks where available.", priceFrom: "Rs 500" },
    ],
    features: [
      { title: "Short waits", description: "Appointment-based flow." },
      { title: "Clear advice", description: "Practical treatment guidance." },
      { title: "Family focus", description: "Kids and adults welcome." },
      { title: "Nearby care", description: "Local clinic convenience." },
    ],
    faqs: [{ q: "Emergency?", a: "For emergencies go to nearest hospital ER; we help with routine care." }],
    galleryLabels: ["Consult", "Waiting", "Checkup", "Pharmacy link"],
    trustPoints: ["Appointments", "Family GP", "Clear advice", "Local"],
    packages: [
      { name: "Consult", price: "Rs 1,500", items: ["Visit"] },
      { name: "Family", price: "Custom", items: ["Multi-patient"], highlighted: true },
      { name: "Follow-up", price: "Rs 1,000", items: ["Review"] },
    ],
    specialSections: ["booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! Clinic appointment: ",
  }),
  lab: n({
    id: "lab",
    label: "Lab",
    family: "health",
    mapsSearches: ["pathology lab", "diagnostic center"],
    tagline: "Pathology lab & home sampling",
    heroTitle: "Accurate tests. Fast reports. Easy booking.",
    heroSubtitle: "Blood tests, panels and home sample collection with digital reports.",
    ctaPrimary: "Book test",
    ctaSecondary: "Ask home sampling",
    bookingLabel: "Book lab test",
    servicesTitle: "Lab tests",
    services: [
      { title: "Blood tests", description: "CBC, sugar, lipid and more.", priceFrom: "Rs 800", popular: true },
      { title: "Full body panel", description: "Comprehensive packages.", priceFrom: "Custom" },
      { title: "Home sampling", description: "Collector visits your home.", priceFrom: "Rs 300+" },
      { title: "Digital report", description: "WhatsApp / online report delivery.", priceFrom: "Included" },
    ],
    features: [
      { title: "Home collection", description: "Save a trip — book sampling at home." },
      { title: "Fast reporting", description: "Most routine tests same/next day." },
      { title: "Package savings", description: "Panels cheaper than single tests." },
      { title: "Doctor friendly", description: "Reports formatted for physicians." },
    ],
    faqs: [{ q: "Fasting required?", a: "Depends on test — we guide you when booking." }],
    galleryLabels: ["Sampling", "Lab", "Report", "Home visit"],
    trustPoints: ["Home sample", "Fast reports", "Packages", "Accurate"],
    packages: [
      { name: "Basic", price: "Custom", items: ["Key tests"] },
      { name: "Executive", price: "Custom", items: ["Full panel"], highlighted: true },
      { name: "Home add-on", price: "Rs 300+", items: ["Collection"] },
    ],
    specialSections: ["booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Lab test booking: ",
  }),
  pharmacy: n({
    id: "pharmacy",
    label: "Pharmacy",
    family: "health",
    mapsSearches: ["medical store"],
    tagline: "Medical store & medicine delivery",
    heroTitle: "Medicines you need — counter or delivery.",
    heroSubtitle: "Prescription medicines, OTC and health supplies with WhatsApp ordering.",
    ctaPrimary: "Order on WhatsApp",
    ctaSecondary: "Ask availability",
    bookingLabel: "Order medicines",
    servicesTitle: "Pharmacy services",
    services: [
      { title: "Prescription fill", description: "Upload prescription photo.", priceFrom: "—", popular: true },
      { title: "OTC & vitamins", description: "Daily care and supplements.", priceFrom: "—" },
      { title: "Local delivery", description: "Nearby delivery where available.", priceFrom: "Rs 100+" },
      { title: "Health devices", description: "BP monitors, nebulizers (as stocked).", priceFrom: "—" },
    ],
    features: [
      { title: "WhatsApp order", description: "Send script photo — we confirm." },
      { title: "Genuine stock", description: "Trusted medical supplies." },
      { title: "Fast packing", description: "Quick counter service." },
      { title: "Substitute advice", description: "Ask pharmacist for options." },
    ],
    faqs: [{ q: "Do you deliver?", a: "In nearby areas — confirm when ordering." }],
    galleryLabels: ["Store", "Counter", "Delivery", "OTC"],
    trustPoints: ["WhatsApp order", "Genuine", "Nearby delivery", "Helpful staff"],
    packages: [
      { name: "Pickup", price: "—", items: ["Counter"] },
      { name: "Delivery", price: "Rs 100+", items: ["Local drop"], highlighted: true },
      { name: "Monthly refill", price: "—", items: ["Reminder order"] },
    ],
    specialSections: ["delivery", "booking"],
    whatsappPreset: "Assalam o Alaikum! Medicine order (prescription attached): ",
  }),
  optician: n({
    id: "optician",
    label: "Optician",
    family: "health",
    mapsSearches: ["optical store", "eye clinic"],
    tagline: "Eyewear & eye checkup",
    heroTitle: "Clear vision. Frames you’ll actually wear.",
    heroSubtitle: "Eye testing, glasses, lenses and contact lens guidance.",
    ctaPrimary: "Book eye test",
    ctaSecondary: "Ask frame prices",
    bookingLabel: "Book eye test",
    servicesTitle: "Optical services",
    services: [
      { title: "Eye test", description: "Power checkup and prescription.", priceFrom: "Rs 500", popular: true },
      { title: "Glasses", description: "Frames + lenses packages.", priceFrom: "Rs 2,500" },
      { title: "Contact lenses", description: "Fitting and brand options.", priceFrom: "Custom" },
      { title: "Lens only", description: "Replace lenses in your frame.", priceFrom: "Rs 1,800" },
    ],
    features: [
      { title: "Style + comfort", description: "Frames for face shape and budget." },
      { title: "Quick test", description: "Appointment or walk-in testing." },
      { title: "Lens options", description: "Blue cut, progressive and more." },
      { title: "Repair", description: "Screw/fit adjustments." },
    ],
    faqs: [{ q: "How long for glasses?", a: "Often 1–3 days depending on lenses." }],
    galleryLabels: ["Frames", "Test", "Lenses", "Kids"],
    trustPoints: ["Eye test", "Frame choice", "Lens options", "Fast ready"],
    packages: [
      { name: "Test", price: "Rs 500", items: ["Checkup"] },
      { name: "Complete pair", price: "Rs 2,500+", items: ["Frame + lens"], highlighted: true },
      { name: "Progressive", price: "Custom", items: ["Premium lens"] },
    ],
    specialSections: ["booking"],
    whatsappPreset: "Assalam o Alaikum! Eye test / glasses: ",
  }),
  nutrition: n({
    id: "nutrition",
    label: "Nutrition",
    family: "health",
    mapsSearches: ["nutritionist", "dietitian"],
    tagline: "Diet plans that fit real life",
    heroTitle: "Eat better with a plan made for you.",
    heroSubtitle: "Weight management, PCOS, diabetes-friendly and sports nutrition coaching.",
    ctaPrimary: "Book diet consult",
    ctaSecondary: "Share your goal",
    bookingLabel: "Book nutritionist",
    servicesTitle: "Nutrition services",
    services: [
      { title: "1:1 consult", description: "Goals, habits and custom plan.", priceFrom: "Rs 3,000", popular: true },
      { title: "Monthly coaching", description: "Weekly check-ins and plan tweaks.", priceFrom: "Rs 8,000" },
      { title: "PCOS / medical", description: "Condition-aware meal guidance.", priceFrom: "Custom" },
      { title: "Online follow-up", description: "WhatsApp support between sessions.", priceFrom: "Included" },
    ],
    features: [
      { title: "Pakistani meals", description: "Plans using local foods you already eat." },
      { title: "Sustainable", description: "No extreme crash diets." },
      { title: "Goal tracking", description: "Weight, energy, labs as relevant." },
      { title: "Family friendly", description: "Home-cook compatible plans." },
    ],
    faqs: [{ q: "Online or in-person?", a: "Both options available." }],
    galleryLabels: ["Consult", "Plan", "Meals", "Progress"],
    trustPoints: ["Local foods", "Coaching", "Medical-aware", "WhatsApp support"],
    packages: [
      { name: "Consult", price: "Rs 3,000", items: ["Plan start"] },
      { name: "Monthly", price: "Rs 8,000", items: ["Coaching"], highlighted: true },
      { name: "Couple", price: "Custom", items: ["Two plans"] },
    ],
    specialSections: ["consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Nutrition consult — goal: ",
  }),
};
