import type { NicheDefinition } from "./types";

const n = (s: NicheDefinition) => s;

export const NICHES_FOOD: Record<string, NicheDefinition> = {
  restaurant: n({
    id: "restaurant",
    label: "Restaurant",
    family: "food",
    mapsSearches: ["restaurant", "family restaurant"],
    tagline: "Family restaurant & dine-in",
    heroTitle: "Flavours your family comes back for.",
    heroSubtitle: "Dine-in, family deals and WhatsApp table booking for weekends.",
    ctaPrimary: "Book a table",
    ctaSecondary: "See menu highlights",
    bookingLabel: "Reserve table",
    servicesTitle: "Menu highlights",
    services: [
      { title: "Family deals", description: "Sharing platters for 4–6 with raita and naan.", priceFrom: "Rs 2,499", popular: true },
      { title: "Karahi & handi", description: "Chicken, mutton and beef karahi cooked to order.", priceFrom: "Rs 1,499" },
      { title: "BBQ grill", description: "Malai boti, seekh, chicken tikka, fish.", priceFrom: "Rs 899" },
      { title: "Chinese / fast fare", description: "Manchurian, fried rice, chow mein.", priceFrom: "Rs 699" },
      { title: "Biryani & rice", description: "Sindhi / Bombay biryani and pulao.", priceFrom: "Rs 450" },
      { title: "Desserts & drinks", description: "Kheer, firni, lassi, fresh juice.", priceFrom: "Rs 250" },
      { title: "Lunch thali", description: "Weekday set meal — fast and filling.", priceFrom: "Rs 499" },
      { title: "Catering trays", description: "Office, dholki and home catering.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Family seating", description: "Comfortable dine-in space." },
      { title: "Weekend booking", description: "Reserve to avoid wait." },
      { title: "Hygiene focus", description: "Clean kitchen standards." },
      { title: "Quick service", description: "Hot food, timely tables." },
    ],
    faqs: [
      { q: "Do you take table bookings?", a: "Yes — WhatsApp your party size and time. Weekends fill up, so book ahead." },
      { q: "Do you deliver?", a: "Ask on WhatsApp for delivery coverage around your area." },
      { q: "Is there a kids / family section?", a: "Family seating is available. Tell us if you need a high-chair or a quieter corner." },
      { q: "Can we order catering trays?", a: "Yes. Share guest count, date and menu preference for a tray quote." },
    ],
    galleryLabels: ["Dining hall", "BBQ grill", "Family table", "Karahi", "Dessert", "Chef plating", "Weekend rush", "Takeaway"],
    trustPoints: ["Family friendly", "Table booking", "Hygiene", "Catering"],
    packages: [
      { name: "Lunch deal", price: "Rs 699", items: ["Set menu"] },
      { name: "Family platter", price: "Rs 2,499", items: ["Share for 4"], highlighted: true },
      { name: "Catering", price: "Custom", items: ["Event trays"] },
    ],
    specialSections: ["menu", "booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Table booking for: ",
  }),
  cafe: n({
    id: "cafe",
    label: "Cafe",
    family: "food",
    mapsSearches: ["cafe", "coffee shop"],
    tagline: "Coffee, bites & work-friendly seats",
    heroTitle: "Good coffee. Calm corner. Your cafe.",
    heroSubtitle: "Specialty coffee, desserts and light bites — perfect for meetups and work.",
    ctaPrimary: "Order / reserve",
    ctaSecondary: "See drinks",
    bookingLabel: "Reserve cafe spot",
    servicesTitle: "Cafe menu",
    services: [
      { title: "Signature coffee", description: "Latte, cappuccino, cold brew.", priceFrom: "Rs 450", popular: true },
      { title: "Desserts", description: "Cakes, brownies, cookies.", priceFrom: "Rs 350" },
      { title: "Light bites", description: "Sandwiches and snacks.", priceFrom: "Rs 500" },
      { title: "Takeaway", description: "Quick pickup orders.", priceFrom: "—" },
    ],
    features: [
      { title: "Wifi friendly", description: "Work and study seats." },
      { title: "Fresh bakes", description: "Daily dessert rotation." },
      { title: "Pickup ready", description: "Order ahead on WhatsApp." },
      { title: "Meetup space", description: "Casual tables for friends." },
    ],
    faqs: [{ q: "Do you host small events?", a: "Message for cake/celebration options." }],
    galleryLabels: ["Coffee", "Dessert", "Seating", "Latte art"],
    trustPoints: ["Specialty coffee", "Wifi", "Pickup", "Desserts"],
    packages: [
      { name: "Coffee + cake", price: "Rs 799", items: ["Combo"] },
      { name: "Office tray", price: "Custom", items: ["Bulk coffee"], highlighted: true },
      { name: "Celebration", price: "Custom", items: ["Cake order"] },
    ],
    specialSections: ["menu", "booking"],
    whatsappPreset: "Assalam o Alaikum! Cafe order/reserve: ",
  }),
  bakery: n({
    id: "bakery",
    label: "Bakery",
    family: "food",
    mapsSearches: ["bakery", "cake shop"],
    tagline: "Custom cakes & fresh bakery",
    heroTitle: "Cakes made for your celebration.",
    heroSubtitle: "Birthday cakes, cupcakes, biscuits and custom designs — order on WhatsApp.",
    ctaPrimary: "Order cake",
    ctaSecondary: "Send design idea",
    bookingLabel: "Order bakery item",
    servicesTitle: "Bakery items",
    services: [
      { title: "Custom cakes", description: "Theme cakes for birthdays & events.", priceFrom: "Rs 2,500", popular: true },
      { title: "Cupcakes", description: "Dozen packs for parties.", priceFrom: "Rs 1,800" },
      { title: "Fresh bakery", description: "Bread, biscuits, snacks.", priceFrom: "Rs 100+" },
      { title: "Wedding cake", description: "Multi-tier celebration cakes.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Custom designs", description: "Share reference photos." },
      { title: "Advance order", description: "Book early for weekends." },
      { title: "Fresh bake", description: "Same-day freshness focus." },
      { title: "Pickup / delivery", description: "Confirm coverage in chat." },
    ],
    faqs: [{ q: "Same-day cakes?", a: "Sometimes — depends on design complexity and stock." }],
    galleryLabels: ["Birthday", "Cupcakes", "Wedding", "Cookies"],
    trustPoints: ["Custom cakes", "Fresh", "Photo orders", "Events"],
    packages: [
      { name: "1 lb cake", price: "Rs 2,500+", items: ["Custom"] },
      { name: "Party pack", price: "Rs 4,500", items: ["Cake + cupcakes"], highlighted: true },
      { name: "Wedding", price: "Custom", items: ["Tiered"] },
    ],
    specialSections: ["menu-cards", "booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Cake order — date & design: ",
  }),
  "cloud-kitchen": n({
    id: "cloud-kitchen",
    label: "Cloud kitchen",
    family: "food",
    mapsSearches: ["cloud kitchen", "tiffin service"],
    tagline: "Delivery kitchen & tiffin",
    heroTitle: "Homestyle meals, delivered hot.",
    heroSubtitle: "Tiffin plans, daily desi meals and catering trays — order on WhatsApp.",
    ctaPrimary: "Order meal",
    ctaSecondary: "Ask tiffin plans",
    bookingLabel: "Place food order",
    servicesTitle: "Kitchen menu",
    services: [
      { title: "Daily tiffin", description: "Lunch/dinner subscription.", priceFrom: "Rs 8,000/mo", popular: true },
      { title: "Single meals", description: "Fresh desi thali style orders.", priceFrom: "Rs 350" },
      { title: "Party trays", description: "Office and home gatherings.", priceFrom: "Custom" },
      { title: "Diet meals", description: "Lighter calorie-aware options.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Consistent taste", description: "Same kitchen standards daily." },
      { title: "Subscription easy", description: "Pause/skip via WhatsApp." },
      { title: "Office delivery", description: "Bulk lunch for teams." },
      { title: "Hygienic pack", description: "Sealed packaging." },
    ],
    faqs: [{ q: "Delivery areas?", a: "Shared when you message your society/area." }],
    galleryLabels: ["Thali", "Tiffin", "Trays", "Packaging"],
    trustPoints: ["Tiffin plans", "Hot delivery", "Office trays", "Hygiene"],
    packages: [
      { name: "Weekly", price: "Custom", items: ["5 days"] },
      { name: "Monthly tiffin", price: "Rs 8,000+", items: ["Daily meals"], highlighted: true },
      { name: "Tray order", price: "Custom", items: ["Event"] },
    ],
    specialSections: ["menu", "delivery", "booking"],
    whatsappPreset: "Assalam o Alaikum! Food/tiffin order: ",
  }),
  catering: n({
    id: "catering",
    label: "Catering",
    family: "food",
    mapsSearches: ["catering service"],
    tagline: "Event catering for home & hall",
    heroTitle: "Catering that makes hosts look good.",
    heroSubtitle: "Wedding, dholki, office and home party catering with setup options.",
    ctaPrimary: "Get catering quote",
    ctaSecondary: "Share guest count",
    bookingLabel: "Request catering quote",
    servicesTitle: "Catering services",
    services: [
      { title: "Home party", description: "Menus for 20–50 guests.", priceFrom: "Custom", popular: true },
      { title: "Wedding catering", description: "Large-scale event menus.", priceFrom: "Custom" },
      { title: "Office lunch", description: "Corporate trays and live counters.", priceFrom: "Custom" },
      { title: "Wait staff add-on", description: "Service team on request.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Menu tasting", description: "Available for larger bookings." },
      { title: "Per-head clarity", description: "Transparent guest-count pricing." },
      { title: "On-time service", description: "Event timeline respected." },
      { title: "Setup help", description: "Buffet layout support." },
    ],
    faqs: [{ q: "Minimum guests?", a: "Depends on menu — shared in quote." }],
    galleryLabels: ["Buffet", "Live station", "Wedding", "Office"],
    trustPoints: ["Per-head quote", "Events", "Setup", "On-time"],
    packages: [
      { name: "Basic", price: "Custom", items: ["Buffet"] },
      { name: "Premium", price: "Custom", items: ["Live + dessert"], highlighted: true },
      { name: "Corporate", price: "Custom", items: ["Lunch trays"] },
    ],
    specialSections: ["menu", "booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! Catering quote — guests/date: ",
  }),
  juice: n({
    id: "juice",
    label: "Juice / smoothie",
    family: "food",
    mapsSearches: ["juice bar"],
    tagline: "Fresh juices & smoothies",
    heroTitle: "Fresh pressed. Bright energy.",
    heroSubtitle: "Seasonal juices, smoothies and healthy blends — dine-in or takeaway.",
    ctaPrimary: "Order juice",
    ctaSecondary: "See specials",
    bookingLabel: "Order juices",
    servicesTitle: "Juice bar",
    services: [
      { title: "Fresh juices", description: "Orange, apple, carrot mixes.", priceFrom: "Rs 250", popular: true },
      { title: "Smoothies", description: "Banana, berry and protein blends.", priceFrom: "Rs 350" },
      { title: "Detox mixes", description: "Green blends and seasonal shots.", priceFrom: "Rs 300" },
      { title: "Combo deals", description: "Juice + snack offers.", priceFrom: "Rs 499" },
    ],
    features: [
      { title: "Made to order", description: "Blended fresh after you order." },
      { title: "Seasonal fruits", description: "Menu follows market freshness." },
      { title: "Quick takeaway", description: "Fast counter service." },
      { title: "Hygiene", description: "Clean blenders and sealed cups." },
    ],
    faqs: [{ q: "Sugar-free options?", a: "Yes — ask for less/no sugar." }],
    galleryLabels: ["Juice", "Smoothie", "Detox", "Counter"],
    trustPoints: ["Fresh blend", "Seasonal", "Takeaway", "Combos"],
    packages: [
      { name: "Classic", price: "Rs 250", items: ["Juice"] },
      { name: "Fitness", price: "Rs 399", items: ["Smoothie"], highlighted: true },
      { name: "Family pack", price: "Custom", items: ["4 cups"] },
    ],
    specialSections: ["menu", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Juice order: ",
  }),
  sweets: n({
    id: "sweets",
    label: "Sweets",
    family: "food",
    mapsSearches: ["sweet shop", "mithai"],
    tagline: "Fresh mithai & celebratory boxes",
    heroTitle: "Mithai for Eid, weddings & everyday joy.",
    heroSubtitle: "Fresh sweets, gift boxes and bulk orders for events.",
    ctaPrimary: "Order mithai",
    ctaSecondary: "Ask today’s fresh",
    bookingLabel: "Order sweets",
    servicesTitle: "Sweet shop",
    services: [
      { title: "Fresh mithai", description: "Daily classic sweets.", priceFrom: "Rs 1,200/kg", popular: true },
      { title: "Gift boxes", description: "Assorted packs for gifting.", priceFrom: "Rs 1,500" },
      { title: "Wedding bulk", description: "Large event quantities.", priceFrom: "Custom" },
      { title: "Specialty items", description: "Seasonal and premium sweets.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Fresh daily", description: "Made for same-day freshness." },
      { title: "Gift ready", description: "Beautiful boxes for occasions." },
      { title: "Bulk orders", description: "Advance booking for weddings." },
      { title: "Custom mix", description: "Build your own assortment." },
    ],
    faqs: [{ q: "Do you deliver gift boxes?", a: "In nearby areas — confirm on WhatsApp." }],
    galleryLabels: ["Mithai", "Gift box", "Display", "Wedding"],
    trustPoints: ["Fresh daily", "Gift boxes", "Bulk events", "Custom mix"],
    packages: [
      { name: "1kg classic", price: "Rs 1,200+", items: ["Fresh"] },
      { name: "Gift box", price: "Rs 1,500+", items: ["Assorted"], highlighted: true },
      { name: "Wedding", price: "Custom", items: ["Bulk"] },
    ],
    specialSections: ["menu-cards", "delivery", "booking"],
    whatsappPreset: "Assalam o Alaikum! Mithai order: ",
  }),
  hotel: n({
    id: "hotel",
    label: "Hotel / PG",
    family: "food",
    mapsSearches: ["hotel", "guest house", "PG hostel"],
    tagline: "Rooms, guest house & PG stays",
    heroTitle: "Comfortable stay. Easy booking.",
    heroSubtitle: "Clean rooms, guest house and PG options with WhatsApp reservation.",
    ctaPrimary: "Check availability",
    ctaSecondary: "Ask room rates",
    bookingLabel: "Book stay",
    servicesTitle: "Stay options",
    services: [
      { title: "Standard room", description: "Clean room with essentials.", priceFrom: "Rs 3,500", popular: true },
      { title: "Family room", description: "More space for families.", priceFrom: "Rs 5,500" },
      { title: "PG / monthly", description: "Longer stay packages.", priceFrom: "Custom" },
      { title: "Corporate stay", description: "Business traveler friendly.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Clean rooms", description: "Daily housekeeping standards." },
      { title: "Easy booking", description: "Confirm on WhatsApp fast." },
      { title: "Location convenience", description: "Near key city areas." },
      { title: "Flexible stays", description: "Nightly and monthly options." },
    ],
    faqs: [{ q: "ID required?", a: "Yes — valid ID at check-in." }],
    galleryLabels: ["Room", "Lobby", "Bathroom", "Exterior"],
    trustPoints: ["Clean stay", "WhatsApp book", "Family rooms", "PG options"],
    packages: [
      { name: "Nightly", price: "Rs 3,500+", items: ["Room"] },
      { name: "Weekly", price: "Custom", items: ["Discounted"], highlighted: true },
      { name: "Monthly PG", price: "Custom", items: ["Long stay"] },
    ],
    specialSections: ["booking"],
    whatsappPreset: "Assalam o Alaikum! Room availability for dates: ",
  }),
  homestay: n({
    id: "homestay",
    label: "Homestay",
    family: "food",
    mapsSearches: ["homestay", "Airbnb host"],
    tagline: "Homestay & short rentals",
    heroTitle: "Feel at home — local stays done right.",
    heroSubtitle: "Private rooms and full apartments for short stays with local hospitality.",
    ctaPrimary: "Check dates",
    ctaSecondary: "Ask amenities",
    bookingLabel: "Book homestay",
    servicesTitle: "Stay types",
    services: [
      { title: "Private room", description: "Comfortable room in shared home.", priceFrom: "Custom", popular: true },
      { title: "Full apartment", description: "Entire place for families.", priceFrom: "Custom" },
      { title: "Weekly stay", description: "Better rates for longer trips.", priceFrom: "Custom" },
      { title: "Family hosting", description: "Local tips and warm welcome.", priceFrom: "—" },
    ],
    features: [
      { title: "Homely comfort", description: "Not a sterile hotel vibe." },
      { title: "Self check-in options", description: "Where available." },
      { title: "Kitchen access", description: "On selected listings." },
      { title: "Local guidance", description: "Food and travel tips." },
    ],
    faqs: [{ q: "Are utilities included?", a: "Usually yes for short stays — confirmed in booking." }],
    galleryLabels: ["Bedroom", "Living", "Kitchen", "View"],
    trustPoints: ["Homely", "Flexible dates", "Family friendly", "Local tips"],
    packages: [
      { name: "Nightly", price: "Custom", items: ["Room/apt"] },
      { name: "Weekly", price: "Custom", items: ["Save more"], highlighted: true },
      { name: "Monthly", price: "Custom", items: ["Long stay"] },
    ],
    specialSections: ["booking"],
    whatsappPreset: "Assalam o Alaikum! Homestay dates: ",
  }),
};
