import type { NicheDefinition } from "./types";

const n = (s: NicheDefinition) => s;

export const NICHES_PROFESSIONAL: Record<string, NicheDefinition> = {
  lawyer: n({
    id: "lawyer",
    label: "Lawyer",
    family: "professional",
    mapsSearches: ["advocate", "law firm"],
    tagline: "Legal consultation & advocacy",
    heroTitle: "Clear legal guidance when it matters.",
    heroSubtitle: "Civil, family and business consultations with confidential appointments.",
    ctaPrimary: "Book consultation",
    ctaSecondary: "Describe matter briefly",
    bookingLabel: "Book legal consult",
    servicesTitle: "Legal services",
    services: [
      { title: "Consultation", description: "Case assessment and options.", priceFrom: "Rs 3,000", popular: true },
      { title: "Family matters", description: "Guidance on family legal issues.", priceFrom: "Custom" },
      { title: "Property / civil", description: "Documentation and dispute support.", priceFrom: "Custom" },
      { title: "Business contracts", description: "Agreement review and drafting help.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Confidential", description: "Private discussion of your matter." },
      { title: "Practical options", description: "Clear next steps, not jargon only." },
      { title: "Appointment based", description: "Dedicated time for your case." },
      { title: "Document guidance", description: "What to prepare before meeting." },
    ],
    faqs: [{ q: "First meeting free?", a: "Depends — ask when booking; consult fees shared upfront." }],
    galleryLabels: ["Office", "Consult", "Documents", "Meeting"],
    trustPoints: ["Confidential", "Clear advice", "Appointments", "Documentation help"],
    packages: [
      { name: "Consult", price: "Rs 3,000+", items: ["Assessment"] },
      { name: "Case handling", price: "Custom", items: ["Representation"], highlighted: true },
      { name: "Contract review", price: "Custom", items: ["Document"] },
    ],
    specialSections: ["consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Legal consultation regarding: ",
  }),
  "ca-accountant": n({
    id: "ca-accountant",
    label: "CA / accountant",
    family: "professional",
    mapsSearches: ["chartered accountant", "tax consultant"],
    tagline: "Tax, NTN & accounting help",
    heroTitle: "Tax and accounts without the stress.",
    heroSubtitle: "NTN, returns, bookkeeping and business tax consulting for freelancers and SMEs.",
    ctaPrimary: "Book tax consult",
    ctaSecondary: "Ask about filing",
    bookingLabel: "Book accountant",
    servicesTitle: "Accounting services",
    services: [
      { title: "Tax filing", description: "Individual and business returns.", priceFrom: "Custom", popular: true },
      { title: "NTN / registration", description: "Help with registrations.", priceFrom: "Custom" },
      { title: "Bookkeeping", description: "Monthly accounts for SMEs.", priceFrom: "Custom" },
      { title: "Freelancer tax", description: "Guidance for online earners.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Deadline aware", description: "We keep filing timelines clear." },
      { title: "SME friendly", description: "Practical packages for small business." },
      { title: "WhatsApp docs", description: "Share documents securely in chat." },
      { title: "Plain language", description: "Explain tax steps simply." },
    ],
    faqs: [{ q: "Online process?", a: "Yes — many steps can start via WhatsApp documents." }],
    galleryLabels: ["Desk", "Filing", "Reports", "Consult"],
    trustPoints: ["Filing help", "SME focus", "Freelancer aware", "Clear fees"],
    packages: [
      { name: "Return filing", price: "Custom", items: ["Individual/biz"] },
      { name: "Monthly books", price: "Custom", items: ["Bookkeeping"], highlighted: true },
      { name: "Consult", price: "Custom", items: ["Advice"] },
    ],
    specialSections: ["consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Tax/accounts help needed: ",
  }),
  "real-estate": n({
    id: "real-estate",
    label: "Real estate agent",
    family: "professional",
    mapsSearches: ["realtor", "property dealer"],
    tagline: "Property dealer & listings",
    heroTitle: "Find or sell property with a local expert.",
    heroSubtitle: "Homes, plots and rentals — verified listings and viewing appointments.",
    ctaPrimary: "Share requirement",
    ctaSecondary: "List my property",
    bookingLabel: "Request property help",
    servicesTitle: "Property services",
    services: [
      { title: "Buy assistance", description: "Match budget and area.", priceFrom: "—", popular: true },
      { title: "Sell / rent listing", description: "Market your property.", priceFrom: "—" },
      { title: "Site visits", description: "Scheduled viewings.", priceFrom: "—" },
      { title: "Investment advice", description: "Area and budget guidance.", priceFrom: "—" },
    ],
    features: [
      { title: "Local market", description: "Society and area knowledge." },
      { title: "Requirement first", description: "We shortlist to your brief." },
      { title: "Viewing slots", description: "Organized property visits." },
      { title: "Deal support", description: "Negotiation and paperwork guidance." },
    ],
    faqs: [{ q: "Commission?", a: "Standard market practice — confirmed upfront." }],
    galleryLabels: ["Home", "Plot", "Apartment", "Visit"],
    trustPoints: ["Local expert", "Shortlist", "Viewings", "Deal support"],
    packages: [
      { name: "Buyer search", price: "—", items: ["Shortlist"] },
      { name: "Seller listing", price: "—", items: ["Market"], highlighted: true },
      { name: "Rental", price: "—", items: ["Tenant/owner"] },
    ],
    specialSections: ["consultation", "portfolio", "booking"],
    whatsappPreset: "Assalam o Alaikum! Property requirement: ",
  }),
  insurance: n({
    id: "insurance",
    label: "Insurance agent",
    family: "professional",
    mapsSearches: ["insurance agent"],
    tagline: "Insurance advisory",
    heroTitle: "The right cover explained simply.",
    heroSubtitle: "Health, life, car and business insurance guidance with claim support basics.",
    ctaPrimary: "Get insurance advice",
    ctaSecondary: "Compare options",
    bookingLabel: "Book insurance consult",
    servicesTitle: "Insurance types",
    services: [
      { title: "Health insurance", description: "Family health cover options.", priceFrom: "—", popular: true },
      { title: "Life insurance", description: "Protection planning.", priceFrom: "—" },
      { title: "Auto insurance", description: "Car/bike policy guidance.", priceFrom: "—" },
      { title: "Business cover", description: "Shop and liability options.", priceFrom: "—" },
    ],
    features: [
      { title: "Needs analysis", description: "Cover matched to your situation." },
      { title: "Plain comparison", description: "Pros/cons without pressure." },
      { title: "Paperwork help", description: "Application support." },
      { title: "Claim guidance", description: "What to do when you need to claim." },
    ],
    faqs: [{ q: "Are you tied to one company?", a: "We advise options — ask which products we can offer." }],
    galleryLabels: ["Consult", "Family", "Auto", "Policy"],
    trustPoints: ["Needs-based", "Clear compare", "Paperwork", "Claim tips"],
    packages: [
      { name: "Health", price: "—", items: ["Quote"] },
      { name: "Family plan", price: "—", items: ["Review"], highlighted: true },
      { name: "Auto", price: "—", items: ["Policy"] },
    ],
    specialSections: ["consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Insurance advice for: ",
  }),
  photographer: n({
    id: "photographer",
    label: "Photographer",
    family: "professional",
    mapsSearches: ["wedding photographer", "studio"],
    tagline: "Wedding & studio photography",
    heroTitle: "Moments captured with cinematic care.",
    heroSubtitle: "Weddings, events and studio portraits — packages with edited delivery.",
    ctaPrimary: "Book shoot date",
    ctaSecondary: "View portfolio",
    bookingLabel: "Book photography",
    servicesTitle: "Photography packages",
    services: [
      { title: "Wedding coverage", description: "Barat/walima full day options.", priceFrom: "Custom", popular: true },
      { title: "Event shoot", description: "Birthdays, corporate, parties.", priceFrom: "Custom" },
      { title: "Studio portraits", description: "Family and professional portraits.", priceFrom: "Rs 8,000" },
      { title: "Cinematics", description: "Highlight films where offered.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Edited delivery", description: "Color-graded final photos." },
      { title: "Timeline clarity", description: "Delivery dates agreed upfront." },
      { title: "Second shooter", description: "Available for large weddings." },
      { title: "Album options", description: "Print/album add-ons." },
    ],
    faqs: [{ q: "Travel outside city?", a: "Yes with travel charges — ask for quote." }],
    galleryLabels: ["Wedding", "Portrait", "Event", "Studio"],
    trustPoints: ["Portfolio proven", "Edited delivery", "Event ready", "Clear packages"],
    packages: [
      { name: "Studio", price: "Rs 8,000+", items: ["Portraits"] },
      { name: "Wedding", price: "Custom", items: ["Full coverage"], highlighted: true },
      { name: "Event", price: "Custom", items: ["Hours-based"] },
    ],
    specialSections: ["portfolio", "booking"],
    whatsappPreset: "Assalam o Alaikum! Photography booking — event/date: ",
  }),
  "event-planner": n({
    id: "event-planner",
    label: "Event planner",
    family: "professional",
    mapsSearches: ["event management"],
    tagline: "Event management & décor",
    heroTitle: "Events planned end-to-end — you enjoy the day.",
    heroSubtitle: "Weddings, corporate and private events with décor, vendors and timeline control.",
    ctaPrimary: "Plan my event",
    ctaSecondary: "Share event type",
    bookingLabel: "Book event consult",
    servicesTitle: "Event services",
    services: [
      { title: "Wedding planning", description: "Full or partial planning.", priceFrom: "Custom", popular: true },
      { title: "Corporate events", description: "Conferences, launches, dinners.", priceFrom: "Custom" },
      { title: "Décor & theme", description: "Stage, floral and lighting concepts.", priceFrom: "Custom" },
      { title: "Vendor management", description: "Coordinate catering, sound, photo.", priceFrom: "—" },
    ],
    features: [
      { title: "Timeline mastery", description: "Run-of-show for the big day." },
      { title: "Vendor network", description: "Trusted local partners." },
      { title: "Budget tracking", description: "Spend aligned to priorities." },
      { title: "On-ground team", description: "Day-of coordination." },
    ],
    faqs: [{ q: "Small events too?", a: "Yes — birthdays and intimate gatherings welcome." }],
    galleryLabels: ["Wedding", "Stage", "Corporate", "Décor"],
    trustPoints: ["Full planning", "Vendors", "Budget aware", "Day-of team"],
    packages: [
      { name: "Partial", price: "Custom", items: ["Selected services"] },
      { name: "Full planning", price: "Custom", items: ["End-to-end"], highlighted: true },
      { name: "Décor only", price: "Custom", items: ["Theme"] },
    ],
    specialSections: ["portfolio", "consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Event planning — type/date/guests: ",
  }),
  travel: n({
    id: "travel",
    label: "Travel agent",
    family: "professional",
    mapsSearches: ["travel agency"],
    tagline: "Tickets, tours & travel packages",
    heroTitle: "Travel sorted — tickets, hotels, tours.",
    heroSubtitle: "Domestic and international trip planning with package options.",
    ctaPrimary: "Plan my trip",
    ctaSecondary: "Ask package ideas",
    bookingLabel: "Request travel plan",
    servicesTitle: "Travel services",
    services: [
      { title: "Flight tickets", description: "Best available fare guidance.", priceFrom: "—", popular: true },
      { title: "Tour packages", description: "Northern areas and more.", priceFrom: "Custom" },
      { title: "Hotel booking", description: "Stay options for your dates.", priceFrom: "—" },
      { title: "Group tours", description: "Family and corporate groups.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Itinerary help", description: "Day-by-day trip outlines." },
      { title: "Budget options", description: "Economy to premium choices." },
      { title: "Document tips", description: "What you need before flying." },
      { title: "WhatsApp support", description: "Updates while you travel-plan." },
    ],
    faqs: [{ q: "Umrah/visa too?", a: "Ask — many agents partner for visa/Umrah services." }],
    galleryLabels: ["North", "Beach", "City", "Group"],
    trustPoints: ["Packages", "Tickets", "Itineraries", "Group tours"],
    packages: [
      { name: "Ticket only", price: "—", items: ["Flights"] },
      { name: "Tour package", price: "Custom", items: ["Trip"], highlighted: true },
      { name: "Custom itinerary", price: "Custom", items: ["Bespoke"] },
    ],
    specialSections: ["consultation", "booking", "portfolio"],
    whatsappPreset: "Assalam o Alaikum! Travel plan — destination/dates: ",
  }),
  visa: n({
    id: "visa",
    label: "Visa consultant",
    family: "professional",
    mapsSearches: ["immigration consultant"],
    tagline: "Visa & immigration consultancy",
    heroTitle: "Visa guidance with clear document checklists.",
    heroSubtitle: "Visit, study and work visa consultancy with application support.",
    ctaPrimary: "Book visa consult",
    ctaSecondary: "Ask required documents",
    bookingLabel: "Book visa consult",
    servicesTitle: "Visa services",
    services: [
      { title: "Visit visa", description: "Tourist/visit file guidance.", priceFrom: "Custom", popular: true },
      { title: "Study visa", description: "Admission + file support paths.", priceFrom: "Custom" },
      { title: "Work / skilled", description: "Pathway assessment where applicable.", priceFrom: "Custom" },
      { title: "Document checklist", description: "What to prepare before filing.", priceFrom: "—" },
    ],
    features: [
      { title: "Checklist first", description: "Know exact documents needed." },
      { title: "Honest assessment", description: "We say if a profile is weak." },
      { title: "File preparation", description: "Organize application materials." },
      { title: "Update tracking", description: "Status communication." },
    ],
    faqs: [{ q: "Guarantee visa?", a: "No ethical consultant guarantees approval — we maximize file quality." }],
    galleryLabels: ["Consult", "Documents", "Checklist", "Office"],
    trustPoints: ["Honest advice", "Checklists", "File prep", "Updates"],
    packages: [
      { name: "Assessment", price: "Custom", items: ["Profile"] },
      { name: "Full file", price: "Custom", items: ["End-to-end"], highlighted: true },
      { name: "Document review", price: "Custom", items: ["Check"] },
    ],
    specialSections: ["consultation", "booking"],
    whatsappPreset: "Assalam o Alaikum! Visa consult — country/type: ",
  }),
};

export const NICHES_RETAIL: Record<string, NicheDefinition> = {
  boutique: n({
    id: "boutique",
    label: "Boutique",
    family: "retail",
    mapsSearches: ["boutique", "clothing store"],
    tagline: "Boutique fashion & stitching",
    heroTitle: "New arrivals you’ll want to wear now.",
    heroSubtitle: "Pret, formals and stitching — order on WhatsApp or visit the boutique.",
    ctaPrimary: "Shop / inquire",
    ctaSecondary: "Ask latest collection",
    bookingLabel: "Ask about outfit",
    servicesTitle: "Boutique offerings",
    services: [
      { title: "New collection", description: "Seasonal pret and formals.", priceFrom: "—", popular: true },
      { title: "Stitching", description: "Custom stitching and alterations.", priceFrom: "Custom" },
      { title: "Bridal / formal", description: "Event wear options.", priceFrom: "Custom" },
      { title: "WhatsApp order", description: "Size + design confirmation in chat.", priceFrom: "—" },
    ],
    features: [
      { title: "Latest styles", description: "Fresh drops regularly." },
      { title: "Size help", description: "Guidance for the right fit." },
      { title: "Stitching desk", description: "Alterations and custom work." },
      { title: "Easy ordering", description: "Reserve pieces on WhatsApp." },
    ],
    faqs: [{ q: "Exchange policy?", a: "Shared at purchase — ask before ordering." }],
    galleryLabels: ["Pret", "Formal", "Bridal", "Store"],
    trustPoints: ["New arrivals", "Stitching", "WhatsApp order", "Fit help"],
    packages: [
      { name: "Pret", price: "—", items: ["Ready to wear"] },
      { name: "Stitched", price: "Custom", items: ["Custom fit"], highlighted: true },
      { name: "Formal", price: "Custom", items: ["Event"] },
    ],
    specialSections: ["portfolio", "booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Boutique inquiry — looking for: ",
  }),
  jewelry: n({
    id: "jewelry",
    label: "Jewelry",
    family: "retail",
    mapsSearches: ["jeweller", "gold shop"],
    tagline: "Gold & jewellery store",
    heroTitle: "Trusted jewellery for every occasion.",
    heroSubtitle: "Gold, diamond and artificial options — bridal sets and daily wear.",
    ctaPrimary: "Inquire design",
    ctaSecondary: "Ask today’s rate info",
    bookingLabel: "Jewellery inquiry",
    servicesTitle: "Jewellery",
    services: [
      { title: "Gold jewellery", description: "Sets and daily wear.", priceFrom: "—", popular: true },
      { title: "Bridal sets", description: "Complete bridal jewellery.", priceFrom: "Custom" },
      { title: "Making / custom", description: "Custom design orders.", priceFrom: "Custom" },
      { title: "Artificial / fashion", description: "Affordable fashion pieces.", priceFrom: "—" },
    ],
    features: [
      { title: "Trusted weighing", description: "Transparent process.", },
      { title: "Bridal expertise", description: "Sets for weddings.", },
      { title: "Design choice", description: "Traditional and modern." },
      { title: "Care tips", description: "How to maintain shine." },
    ],
    faqs: [{ q: "Buyback?", a: "Ask current shop policy when visiting." }],
    galleryLabels: ["Gold", "Bridal", "Rings", "Display"],
    trustPoints: ["Trusted", "Bridal sets", "Custom", "Transparent"],
    packages: [
      { name: "Daily wear", price: "—", items: ["Light pieces"] },
      { name: "Bridal", price: "Custom", items: ["Full set"], highlighted: true },
      { name: "Custom order", price: "Custom", items: ["Made to design"] },
    ],
    specialSections: ["portfolio", "booking", "consultation"],
    whatsappPreset: "Assalam o Alaikum! Jewellery inquiry: ",
  }),
  "mobile-shop": n({
    id: "mobile-shop",
    label: "Mobile shop",
    family: "retail",
    mapsSearches: ["mobile store", "phone repair"],
    tagline: "Mobiles, accessories & repair",
    heroTitle: "Phones, accessories and fast repair.",
    heroSubtitle: "New mobiles, accessories, screen repair and software fixes.",
    ctaPrimary: "Ask price / repair",
    ctaSecondary: "Send phone model",
    bookingLabel: "Mobile inquiry",
    servicesTitle: "Mobile services",
    services: [
      { title: "New mobiles", description: "Popular brands and variants.", priceFrom: "—", popular: true },
      { title: "Screen repair", description: "Display replacement.", priceFrom: "Custom" },
      { title: "Software / FRP", description: "Common software services.", priceFrom: "Rs 1,000+" },
      { title: "Accessories", description: "Covers, chargers, earbuds.", priceFrom: "Rs 200+" },
    ],
    features: [
      { title: "Model advice", description: "Help choose within budget." },
      { title: "Quick repair", description: "Many jobs same day." },
      { title: "Parts quality", description: "OEM/compatible options explained." },
      { title: "Warranty notes", description: "Repair warranty where offered." },
    ],
    faqs: [{ q: "Data safety?", a: "We advise backup before repair when possible." }],
    galleryLabels: ["Phones", "Repair", "Accessories", "Counter"],
    trustPoints: ["Sales + repair", "Same-day fixes", "Accessories", "Budget advice"],
    packages: [
      { name: "Phone buy", price: "—", items: ["Device"] },
      { name: "Screen fix", price: "Custom", items: ["Repair"], highlighted: true },
      { name: "Accessory kit", price: "Custom", items: ["Cover + glass"] },
    ],
    specialSections: ["booking", "warranty"],
    whatsappPreset: "Assalam o Alaikum! Mobile buy/repair — model: ",
  }),
  electronics: n({
    id: "electronics",
    label: "Electronics",
    family: "retail",
    mapsSearches: ["electronics store"],
    tagline: "Home appliances & electronics",
    heroTitle: "Appliances for home — sold with guidance.",
    heroSubtitle: "TVs, fridges, ACs and small appliances with install support options.",
    ctaPrimary: "Ask availability",
    ctaSecondary: "Compare models",
    bookingLabel: "Electronics inquiry",
    servicesTitle: "Electronics",
    services: [
      { title: "Home appliances", description: "Fridge, washing machine, more.", priceFrom: "—", popular: true },
      { title: "TV & audio", description: "Smart TVs and sound.", priceFrom: "—" },
      { title: "Install support", description: "Coordinate installation.", priceFrom: "—" },
      { title: "Warranty guidance", description: "Brand warranty clarity.", priceFrom: "—" },
    ],
    features: [
      { title: "Model compare", description: "Help pick the right specs." },
      { title: "Genuine products", description: "Authorized/reliable sourcing focus." },
      { title: "After support", description: "Service contact guidance." },
      { title: "Delivery options", description: "Ask for local delivery." },
    ],
    faqs: [{ q: "Install included?", a: "Depends on product — confirmed at purchase." }],
    galleryLabels: ["TV", "Fridge", "AC", "Store"],
    trustPoints: ["Compare help", "Genuine focus", "Delivery", "Warranty clarity"],
    packages: [
      { name: "Appliance", price: "—", items: ["Device"] },
      { name: "Bundle", price: "Custom", items: ["Multi-item"], highlighted: true },
      { name: "Install add-on", price: "—", items: ["Setup"] },
    ],
    specialSections: ["booking", "delivery", "warranty"],
    whatsappPreset: "Assalam o Alaikum! Electronics inquiry — need: ",
  }),
  furniture: n({
    id: "furniture",
    label: "Furniture",
    family: "retail",
    mapsSearches: ["furniture store"],
    tagline: "Furniture store & custom orders",
    heroTitle: "Furniture that fits your home and budget.",
    heroSubtitle: "Sofas, beds, dining and custom orders with delivery options.",
    ctaPrimary: "Ask furniture price",
    ctaSecondary: "Send room size",
    bookingLabel: "Furniture inquiry",
    servicesTitle: "Furniture",
    services: [
      { title: "Ready furniture", description: "Sofas, beds, tables in stock styles.", priceFrom: "—", popular: true },
      { title: "Custom order", description: "Made to your measurements.", priceFrom: "Custom" },
      { title: "Office furniture", description: "Desks and workstations.", priceFrom: "Custom" },
      { title: "Delivery & assembly", description: "Home setup support.", priceFrom: "—" },
    ],
    features: [
      { title: "Material options", description: "Budget to premium finishes." },
      { title: "Room planning", description: "Advice for compact Pakistani homes." },
      { title: "Custom sizes", description: "Made-to-measure pieces." },
      { title: "Delivery", description: "Local delivery where available." },
    ],
    faqs: [{ q: "How long for custom?", a: "Shared after design confirmation — often days to weeks." }],
    galleryLabels: ["Sofa", "Bedroom", "Dining", "Custom"],
    trustPoints: ["Ready + custom", "Delivery", "Material choice", "Room advice"],
    packages: [
      { name: "Ready piece", price: "—", items: ["In stock"] },
      { name: "Room set", price: "Custom", items: ["Bundle"], highlighted: true },
      { name: "Custom", price: "Custom", items: ["Made to order"] },
    ],
    specialSections: ["portfolio", "booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Furniture inquiry — looking for: ",
  }),
  "pet-shop": n({
    id: "pet-shop",
    label: "Pet shop",
    family: "retail",
    mapsSearches: ["pet store", "pet grooming"],
    tagline: "Pet shop & grooming",
    heroTitle: "Happy pets. Trusted food & grooming.",
    heroSubtitle: "Pet food, accessories and grooming appointments for dogs and cats.",
    ctaPrimary: "Order / book groom",
    ctaSecondary: "Ask pet food",
    bookingLabel: "Pet shop inquiry",
    servicesTitle: "Pet services",
    services: [
      { title: "Pet food", description: "Trusted brands and sizes.", priceFrom: "—", popular: true },
      { title: "Grooming", description: "Bath, haircut, nail trim.", priceFrom: "Rs 2,000" },
      { title: "Accessories", description: "Leashes, bowls, toys.", priceFrom: "—" },
      { title: "Health basics", description: "Guidance and product support.", priceFrom: "—" },
    ],
    features: [
      { title: "Brand options", description: "Food for different budgets." },
      { title: "Gentle grooming", description: "Calm handling focus." },
      { title: "Appointment slots", description: "Book grooming ahead." },
      { title: "Owner tips", description: "Care advice with purchase." },
    ],
    faqs: [{ q: "Which pets?", a: "Mostly dogs/cats — ask for birds/others." }],
    galleryLabels: ["Food", "Grooming", "Accessories", "Pets"],
    trustPoints: ["Food brands", "Grooming", "Accessories", "Care tips"],
    packages: [
      { name: "Food", price: "—", items: ["Bag"] },
      { name: "Groom", price: "Rs 2,000+", items: ["Full groom"], highlighted: true },
      { name: "Starter kit", price: "Custom", items: ["Essentials"] },
    ],
    specialSections: ["booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Pet food/grooming: ",
  }),
  florist: n({
    id: "florist",
    label: "Florist",
    family: "retail",
    mapsSearches: ["florist", "flower shop"],
    tagline: "Flowers, bouquets & décor",
    heroTitle: "Fresh flowers for love, Eid and events.",
    heroSubtitle: "Bouquets, bridal flowers and event floral décor — order on WhatsApp.",
    ctaPrimary: "Order flowers",
    ctaSecondary: "Send occasion",
    bookingLabel: "Order floral",
    servicesTitle: "Floral services",
    services: [
      { title: "Bouquets", description: "Birthday and surprise bouquets.", priceFrom: "Rs 2,000", popular: true },
      { title: "Bridal flowers", description: "Bridal bouquet and décor accents.", priceFrom: "Custom" },
      { title: "Event décor", description: "Stage and venue florals.", priceFrom: "Custom" },
      { title: "Same-day delivery", description: "Where area and stock allow.", priceFrom: "—" },
    ],
    features: [
      { title: "Fresh stems", description: "Quality-focused flowers." },
      { title: "Custom notes", description: "Add a message card." },
      { title: "Occasion ready", description: "Valentine, Eid, weddings." },
      { title: "Delivery slots", description: "Timed drops when possible." },
    ],
    faqs: [{ q: "Same-day?", a: "Often yes for standard bouquets — confirm early." }],
    galleryLabels: ["Bouquet", "Bridal", "Décor", "Shop"],
    trustPoints: ["Fresh", "Custom cards", "Events", "Delivery"],
    packages: [
      { name: "Bouquet", price: "Rs 2,000+", items: ["Hand bouquet"] },
      { name: "Premium", price: "Rs 4,500+", items: ["Designer"], highlighted: true },
      { name: "Event", price: "Custom", items: ["Décor"] },
    ],
    specialSections: ["booking", "delivery", "portfolio"],
    whatsappPreset: "Assalam o Alaikum! Flower order — occasion/date: ",
  }),
  printing: n({
    id: "printing",
    label: "Printing",
    family: "retail",
    mapsSearches: ["printing press", "flex printing"],
    tagline: "Printing, flex & branding",
    heroTitle: "Print that makes your business visible.",
    heroSubtitle: "Flex, visiting cards, brochures and shop branding prints.",
    ctaPrimary: "Get print quote",
    ctaSecondary: "Send artwork",
    bookingLabel: "Print inquiry",
    servicesTitle: "Printing services",
    services: [
      { title: "Flex / banners", description: "Shop and event flex printing.", priceFrom: "Custom", popular: true },
      { title: "Visiting cards", description: "Business cards fast turnaround.", priceFrom: "Rs 800+" },
      { title: "Brochures / flyers", description: "Marketing print packs.", priceFrom: "Custom" },
      { title: "Shop boards", description: "Signage and branding.", priceFrom: "Custom" },
    ],
    features: [
      { title: "Fast turnaround", description: "Urgent jobs prioritized." },
      { title: "Design help", description: "Basic design support available." },
      { title: "Bulk pricing", description: "Better rates for quantity." },
      { title: "Quality materials", description: "Durable outdoor flex options." },
    ],
    faqs: [{ q: "Do you design?", a: "Basic design yes — complex branding may need extra time." }],
    galleryLabels: ["Flex", "Cards", "Flyer", "Board"],
    trustPoints: ["Fast print", "Flex experts", "Cards", "Shop branding"],
    packages: [
      { name: "Cards", price: "Rs 800+", items: ["Box"] },
      { name: "Flex", price: "Custom", items: ["Banner"], highlighted: true },
      { name: "Campaign pack", price: "Custom", items: ["Multi-print"] },
    ],
    specialSections: ["booking", "portfolio"],
    whatsappPreset: "Assalam o Alaikum! Printing quote — need: ",
  }),
  stationery: n({
    id: "stationery",
    label: "Stationery",
    family: "retail",
    mapsSearches: ["stationery shop"],
    tagline: "Stationery & school supplies",
    heroTitle: "School and office stationery in one place.",
    heroSubtitle: "Books, pens, bags and office supplies — bulk orders welcome.",
    ctaPrimary: "Ask availability",
    ctaSecondary: "Bulk order inquiry",
    bookingLabel: "Stationery inquiry",
    servicesTitle: "Stationery",
    services: [
      { title: "School supplies", description: "Notebooks, pens, geometry, bags.", priceFrom: "—", popular: true },
      { title: "Office stationery", description: "Files, printers supplies, desk needs.", priceFrom: "—" },
      { title: "Bulk / school orders", description: "List-based fulfillment.", priceFrom: "Custom" },
      { title: "Art materials", description: "Colors and craft basics.", priceFrom: "—" },
    ],
    features: [
      { title: "Season ready", description: "Back-to-school stock focus." },
      { title: "Bulk lists", description: "Share list — we pack." },
      { title: "Fair prices", description: "Daily essentials affordably." },
      { title: "Nearby pickup", description: "Quick counter service." },
    ],
    faqs: [{ q: "Do you deliver bulk?", a: "For larger orders in nearby areas — ask." }],
    galleryLabels: ["Notebooks", "Bags", "Office", "Counter"],
    trustPoints: ["School stock", "Bulk lists", "Office supply", "Fair prices"],
    packages: [
      { name: "Student kit", price: "Custom", items: ["Essentials"] },
      { name: "Bulk list", price: "Custom", items: ["Packed order"], highlighted: true },
      { name: "Office restock", price: "Custom", items: ["Monthly"] },
    ],
    specialSections: ["booking", "delivery"],
    whatsappPreset: "Assalam o Alaikum! Stationery — need: ",
  }),
};
